### ISSUE TITLE
Documentation needed 

### ISSUE THREAD

**Issue by ahmedeltaher** [googlesamples/easypermissions#101]
Hello Contributors,
I tried to `use EasyPermissions` inside of  `PermissionsDispatcher` , but unfortunately , I don't find a good documentation for it , and I there is no enough information to use `annotations` . 
Can you build a documentation ? , to make it easy to use .

**Comment by mrzhqiang** [comment]
@ahmedeltaher https://github.com/googlesamples/easypermissions/blob/master/app/src/main/java/pub/devrel/easypermissions/sample/MainActivity.java

**Comment by samtstern** [comment]
@ahmedeltaher is the library you are referring to:
https://github.com/hotchemi/PermissionsDispatcher

I would recommend only using EasyPermissions or PermissionsDispatcher, they do mostly the same thing and using them together could be complicated.

As @mrzhqiang suggested, there is a sample in the `app` folder and documentation in `README.md`
