### ISSUE TITLE
Find a crash

### ISSUE THREAD

**Issue by mrzhqiang** [googlesamples/easypermissions#102]
1.callback EasyPermissions.PermissionCallbacks and show a dialog

```java
onPermissionsDenied(int requestCode, List<String> perms) {
if (EasyPermissions.somePermissionPermanentlyDenied(this, perms)) {
            new AppSettingsDialog.Builder(this)
                    .setRequestCode(requestCode)
                    .build().show();
        }
}
```

2.click OK button
```java
Intent intent = new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);
        Uri uri = Uri.fromParts("package", mContext.getPackageName(), null);
        intent.setData(uri);
```

3.In my app permissions Settings page, Granted, Denied, Granted, and my app just crash.

**Comment by samtstern** [comment]
@mrzhqiang sorry I took so long here, but can you show what the crash is?  Any stack trace would be helpful.

**Comment by mrzhqiang** [comment]
@samtstern  Debug mode, using the sample also is the crash. Run mode, Everything is all right.
Not find useful stack trace.

**Comment by samtstern** [comment]
@mrzhqiang alright well with the amount of information we have, I really can't investigate this.  If you find a stack trace or some more detailed reproduction steps I will be happy to re-open this issue and dig further. Thanks for reporting it!
