### ISSUE TITLE
SDK 23.3.1 does not exists anymore?

### ISSUE THREAD

**Issue by PedroGabriel** [googlesamples/easypermissions#105]
Always getting a 404 but it is getting used inside this plugin gradle

**Comment by SUPERCILEX** [comment]
@PedroGabriel You can (and _**really should**_) use a higher version as long as you override all the support libs used in easypermissions. So for `v0.3.1` of easypermissions, you'll want to add `compile 'com.android.support:appcompat-v7:25.3.1'` to your `build.gradle` file. Hope that clears things up! 😄

**Comment by PedroGabriel** [comment]
@SUPERCILEX it just worked today when I the `com.android.support:appcompat-v7` set to `25.3.1`

Not sure if it was really getting a 404 or I was just in need of sleep haha

Thank you for your explanation, I was not sure if my version was overriding the one set inside easypermissions but it all makes sense now 😄

**Comment by SUPERCILEX** [comment]
@PedroGabriel Glad to clear things up!
