### ISSUE TITLE
how can i set the dialog cancel and ensure text color

### ISSUE THREAD

**Issue by freefly2016** [googlesamples/easypermissions#107]

**Comment by ghuiii** [comment]
I have the same problem, The dialog background is white and the defautl text color also is white, so user cannot see the button

**Comment by samtstern** [comment]
@ghuiii so is all text white throughout your application?  Would you prefer a dark dialog in your case?  EasyPermissions uses the theme from the context you pass in so I believe the color of the buttons will be `colorAccent`

**Comment by ghuiii** [comment]
@samtstern  you're right, thanks.

**Comment by samtstern** [comment]
@ghuiii I assume that means I can close this issue, but please let me know if you need it re-opened.

**Comment by ghuiii** [comment]
@samtstern yes
