### ISSUE TITLE
in xiaomi ,when the location permission in xiaomi is ask not agree ,not refuse,the dialog don't show

### ISSUE THREAD

**Issue by freefly2016** [googlesamples/easypermissions#108]
在小米手机上，第一次 请求定位权限，怎么不弹定位权限请求的弹窗呢？小米默认是询问，不是同意，不是拒绝。

**Comment by samtstern** [comment]
@freefly2016 sorry but I can only provide support on this repo in English, I'd suggest asking this question on StackOverflow maybe someone can help you there!

Also if I understand the title correctly, please check the following:

- Device is running Android 6.0 or greater
- Compile SDK version is 23 or greater
- Permission is declared in `AndroidManifest.xml`
