### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by samtstern** [googlesamples/easypermissions#112]
Need to test:

Different requesting environments:

- Activity
- Fragment (framework)
- Fragment (support lib)
- API < 23

Different types of situations:

- Permission denied
- Permission permanently denied
- App settings screen

**Comment by henriquenfaria** [comment]
@samtstern do you need help with this? The first step imo would be setting up [codecov](https://github.com/codecov/example-android) + jaCoCo to track the progress.

**Comment by samtstern** [comment]
@henriquenfaria thanks for asking!  Sorry for the late response, was on vacation.  Any help here would be great.  If you know how to set up those tools for an Android project I'd gladly accept a pull request!

**Comment by henriquenfaria** [comment]
@samtstern Cool! I will send a PR soon.

**Comment by henriquenfaria** [comment]
@samtstern Just opened [this](https://github.com/googlesamples/easypermissions/pull/224) PR integrating codecov. I didn't write any new tests yet (will do that in another PR when this is merged), just refactored the existing ones a little bit.

**Comment by henriquenfaria** [comment]
@samtstern I've just opened a [PR](https://github.com/googlesamples/easypermissions/pull/227) adding tests for all `requestPermissions()` methods. In a future PR I'll add more tests that will cover all remaining methods of the public api.

**Comment by samtstern** [comment]
@henriquenfaria has slain the testing dragon!
