### ISSUE TITLE
this module can run on android 6.0 systerm well,but cann't run on android 4.0?

### ISSUE THREAD

**Issue by hyf910605** [googlesamples/easypermissions#117]
I just used this module on my project and it can run well on android 6.0 when I refuse the permission and it can show the dialog let me choose again ,this is very well .But when it run on android 4.0 systerm ,it just show the dialog that i just refuse the permission but not let me choose again ,is this a bug ?

**Comment by samtstern** [comment]
@hyf910605 Android 4.0 does not support runtime permissions so, `EasyPermissions.hasPermissions(...)` should always return `true` on those platforms.  You should always call this before calling `requestPermissions` or any related function.
