### ISSUE TITLE
Error:(43, 13) Failed to resolve: pub.devrel:easypermissions:0.4.0

### ISSUE THREAD

**Issue by Uttermost** [googlesamples/easypermissions#121]
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'eu.inmite.android.lib:android-validation-komensky:0.9.4@aar'
    compile 'com.github.clans:fab:1.6.4'
    compile 'com.google.firebase:firebase-auth:9.0.2'
    compile 'com.google.firebase:firebase-database:9.0.2'

    compile 'com.google.firebase:firebase-storage:9.0.2'
    compile 'com.android.support:cardview-v7:25.3.1'
    compile 'com.android.support:recyclerview-v7:25.3.1'
    compile 'com.android.support:support-v4:25.3.1'
    compile 'de.hdodenhof:circleimageview:2.1.0'
    compile 'pub.devrel:easypermissions:0.4.0'
    compile 'com.android.support:multidex:1.0.0'
    testCompile 'junit:junit:4.12'
}
apply plugin: 'com.google.gms.google-services'

**Comment by samtstern** [comment]
Do you have `jcenter()` in your repositories?

```
repositories {
  jcenter()
}

dependencies {
  compile 'pub.devrel:easypermissions:0.4.0'
}
```

**Comment by Uttermost** [comment]
Yes...,

**Comment by Uttermost** [comment]
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.2.2'
        classpath 'com.google.gms:google-services:3.0.0'


        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()

    }
}

**Comment by samtstern** [comment]
Sorry @Uttermost there's not enough information here to debug and I expect there's something wrong with your individual system configuration.  Could you post this on StackOverflow instead?

**Comment by teminnov** [comment]
I've changed the network and Invalid caches/Restart in file menu. Everything fine now...

**Comment by Chinecherem20199** [comment]
change it to implementation and then sync it again
