### ISSUE TITLE
Release new version of EP

### ISSUE THREAD

**Issue by SUPERCILEX** [googlesamples/easypermissions#122]
@samtstern The [leak](https://github.com/googlesamples/easypermissions/commit/871b66d80eff489ce19e083986a632d03b9e6209) was fixed since `0.4` and it would be nice to have a new version of EP released. 😄

**Comment by samtstern** [comment]
Released `0.4.1`.

**Comment by SUPERCILEX** [comment]
@samtstern Awesome! 👍
