### ISSUE TITLE
No callback from OK button on rationale dialog

### ISSUE THREAD

**Issue by socialvanana** [googlesamples/easypermissions#124]
When user click ok button on rationale dialog, then permission request dialog should pops up.

0.2.1 works fine.

I tested 0.3.1 and 0.4.0(latest).
Both of these are not work.

**Comment by SUPERCILEX** [comment]
@socialvanana can't repro, could you share some code?

**Comment by socialvanana** [comment]
This is my code.

`public class ActSplash extends Activity implements EasyPermissions.PermissionCallbacks {
@Override
 protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        test();
    }
    @AfterPermissionGranted(Constant.PERMISSION_WRITE_EXTERNAL_STORAGE)
    private void test() {
        String[] perms = {Manifest.permission.WRITE_EXTERNAL_STORAGE};
        if (EasyPermissions.hasPermissions(this, perms)) {
            
            Intent i = new Intent(this, ActMain.class);
            startActivity(i);
            finish();

        } else {
            EasyPermissions.requestPermissions(this, getString(R.string.permission_rationale),
                    Constant.PERMISSION_WRITE_EXTERNAL_STORAGE, perms);
        }
    }



    @Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);

        // Forward results to EasyPermissions
        EasyPermissions.onRequestPermissionsResult(requestCode, permissions, grantResults, this);
    }

    @Override
    public void onPermissionsGranted(int requestCode, List<String> perms) {
        Logger.loge("11111");
    }

    @Override
    public void onPermissionsDenied(int requestCode, List<String> perms) {
        finish();
    }
}`

**Comment by samtstern** [comment]
@socialvanana does it make a difference if you use an AppCompatActivity instead?

**Comment by socialvanana** [comment]
I just don't want to use an AppCompatActivity till I get problem with an Activity.
and my minSdkVersion is 19. I guess I don't need an AppCompatActivity.

**Comment by samtstern** [comment]
@socialvanana I understand, I just want to help debug so I can find out where the issue is.  If you **temporarily** use an AppCompatActivity does EasyPermissions work?

**Comment by socialvanana** [comment]
I changed 2 things.
0.2.1 to 0.4.0 and Activity to AppCompatActivity.

Yes it works.

**Comment by samtstern** [comment]
@socialvanana thank you! Looks like we have a bug in dealing with plain `Activity` classes then.

**Comment by socialvanana** [comment]
Thank you so much for your effort. This library is super great!

**Comment by samtstern** [comment]
This will be fixed in `0.4.1` which I am releasing momentarily.
