### ISSUE TITLE
在Samsung   SM-N9200 Android 6.0.1  api23会崩溃

### ISSUE THREAD

**Issue by 921668753** [googlesamples/easypermissions#125]
EasyPermissions.requestPermissions(this, getString(R.string.rationale_camera), RC_CAMERA_PERM, Manifest.permission.CAMERA);
时候会崩溃

**Comment by samtstern** [comment]
@921668753 I'm sorry but I have to close this issue since it doesn't contain any debugging information in English.  Maybe try StackOverflow?
