### ISSUE TITLE
Java 1.8

### ISSUE THREAD

**Issue by snodnipper** [googlesamples/easypermissions#128]
It would good to document the language level for EasyPermissions.

I note, for instance, that changing `compile 'pub.devrel:easypermissions:0.4.0'` to `compile 'pub.devrel:easypermissions:0.4.1'` results in a version 52 byte code error in one of my projects.

![error](https://user-images.githubusercontent.com/576719/27126575-d390bae4-50ef-11e7-92ea-4dc887963f6e.png)

**Comment by samtstern** [comment]
@snodnipper thanks for reporting, can you describe what changes you had to make in your project to fix this?  This is the first release with `1.8` compatibility and if it was a real pain for you I may revert back to `1.7` to save the developer experience for library consumers.

**Comment by samtstern** [comment]
@snodnipper I just reverted back to 1.7 and released version `0.4.2` of the library, thanks for flagging this.
