### ISSUE TITLE
Need 'requestCode' in 'onPermissionsGranted' function

### ISSUE THREAD

**Issue by farhan-arbisoft** [googlesamples/easypermissions#13]
Hi,
     I need 'requestCode' in 'onPermissionsGranted' function to uniquely identify the flow.
It would be best if you add them in next update.

**Comment by jmarkovic** [comment]
Hello,

Could you explain your usecase where having request code would benefit you more than using `@AfterPermissionGranted` annotation?

**Comment by farhan-arbisoft** [comment]
I have 2 places in my app where its the requirement to ask permission.

When relevant permissions is granted i want to know the flow(place) from where the permission is asked and granted.

**Comment by samtstern** [comment]
I like this idea, fix comin.
