### ISSUE TITLE
About Changelog File

### ISSUE THREAD

**Issue by GulajavaMinistudio** [googlesamples/easypermissions#131]
Are there any changelog file or changelog.md that we can see in every release version ?

**Comment by samtstern** [comment]
@GulajavaMinistudio sorry I have not been maintaining a changelog, although I really should going forward.  Is there any specific version you're curious about?

**Comment by GulajavaMinistudio** [comment]
Maybe changelog since 0.4.0 and newer version. Since we dont know what's is breaking changes between these versions

**Comment by samtstern** [comment]
@GulajavaMinistudio FYI there have not been any breaking changes in a while, just bugfixes.

**Comment by samtstern** [comment]
We have started doing releases:
https://github.com/googlesamples/easypermissions/releases

And we'll continue this going forward.
