### ISSUE TITLE
EasyPermissions Always Request Phone Call Permission

### ISSUE THREAD

**Issue by Luisfermp18** [googlesamples/easypermissions#132]
Hi,

My problem is that always I call _requestPermissions(...)_ method, the device show request permission for Phone Call, that is my code:

`EasyPermissions.requestPermissions(this, "Grant Access to Device State", REQUEST_STATE_PHONE_READ, Manifest.permission.READ_PHONE_STATE);`

Thank you.

**Comment by samtstern** [comment]
@Luisfermp18 can you explain what is not working?  If you are requesting `READ_PHONE_STATE` you are requesting the Phone permission group.

**Comment by samtstern** [comment]
Closing issue due to lack of response.
