### ISSUE TITLE
@AfterPermissionGranted should also be annotated with @Keep

### ISSUE THREAD

**Issue by loki666** [googlesamples/easypermissions#137]
if using proguard optimization, a @AfterPermissionGranted method could be completly inlined preventing EasyPermissions.onRequestPermissionsResult to find it.

    private static final int REQUEST_PERMISSION = 10;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        navigateToPlayer();
    }

    @Keep
    @AfterPermissionGranted(REQUEST_PERMISSION)
    private void navigateToPlayer() {
        if (EasyPermissions.hasPermissions(this, Manifest.permission.READ_EXTERNAL_STORAGE)) {
            Intent intent = new Intent(this, MusicPlayerActivity.class);
            startActivity(intent);
            finish();
        } else {
            EasyPermissions.requestPermissions(this, getString(R.string.read_permission_rational), REQUEST_PERMISSION, Manifest.permission.READ_EXTERNAL_STORAGE);
        }
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);

        // Forward results to EasyPermissions
        EasyPermissions.onRequestPermissionsResult(requestCode, permissions, grantResults, this);
    }

**Comment by samtstern** [comment]
@loki666 should this be enforced by adding consumer proguard rules to the library?

**Comment by loki666** [comment]
ideally yes

**Comment by loki666** [comment]
this proguard rule seems to do the trick

-keepclasseswithmembers class * {
    @pub.devrel.easypermissions.AfterPermissionGranted <methods>;
}

**Comment by samtstern** [comment]
@loki666 does it work the same if you use `keepclassmembers` instead of `keepclasseswithmembers`?

**Comment by loki666** [comment]
probably yes (not tried)

**Comment by loki666** [comment]
tested ok

**Comment by samtstern** [comment]
This is fixed in version `0.4.3` which was just released.
