### ISSUE TITLE
Crash when request mutil permissions

### ISSUE THREAD

**Issue by YouriZhang** [googlesamples/easypermissions#138]
When I test request Manifest.permission.CAMERA, Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.READ_EXTERNAL_STORAGE;
after all permission denied,activity crashed.

**Comment by samtstern** [comment]
@YouriZhang can you provide some logs from the crash?

**Comment by YouriZhang** [comment]
Thank you for your prompt reply，but unfortunately I can't catch any error logs when crashed. This just occoured when apk first installed and all requested permissions were refused. I can provide the mobile brand which occoured in XiaoMi Note 4.

**Comment by samtstern** [comment]
@YouriZhang hmmm there's not much I can do without an error log or some code that reproduces this.  I am going to close the issue for now but please let me know if you see the issue again,
