### ISSUE TITLE
打电话权限

### ISSUE THREAD

**Issue by isqing** [googlesamples/easypermissions#139]
app在权限列表里并没有打电话的权限，这个权限是禁止的，但是为什么hasPermissions检查时一直说有这个权限，打电话时报 this app not allowed to StartActivity:Intent { act=android.intent.action.CALL dat=tel:xxxxxxxxxxx }的问题，如果把权限改成调摄像头就是对的

**Comment by samtstern** [comment]
@isqing sorry we can only accept issues in English, it's the only language I speak!
