### ISSUE TITLE
where is the rationale message?

### ISSUE THREAD

**Issue by CodingCodersCode** [googlesamples/easypermissions#140]
This is my java code:
![image](https://user-images.githubusercontent.com/18276107/28195949-07166aba-6880-11e7-8057-dccc296dc554.png)

![image](https://user-images.githubusercontent.com/18276107/28196014-872c01b0-6880-11e7-9b53-08f56b79b4b4.png)

and this is the dialog:

![image](https://user-images.githubusercontent.com/18276107/28196031-9eb9fe22-6880-11e7-90e2-58afb459f0d0.png)

What‘s wrong?

**Comment by Waye3** [comment]
how you solved it
