### ISSUE TITLE
why use android.support.v7.app.AlertDialog in RationaleDialogConfig

### ISSUE THREAD

**Issue by andrewlcgu** [googlesamples/easypermissions#142]
If I use Activity not AppCompatActivity, could result the error:
<img width="772" alt="rtx20170724-105944 2x" src="https://user-images.githubusercontent.com/5044141/28506625-3e31fae6-705f-11e7-9a73-caa23b6d4722.png">

**Comment by samtstern** [comment]
This was fixed in #153 and will be included in the next release.

**Comment by samtstern** [comment]
Released in version `1.0.0`
