### ISSUE TITLE
Having a warning in @AfterPermissionGranted()

### ISSUE THREAD

**Issue by Leonid-Kiev** [googlesamples/easypermissions#145]
I am having a warning when trying to access LocationServices  with granted permissions: 

```java
    @AfterPermissionGranted(RC_REQUEST_LOCATION)
    fun enableLocation() {
        val perm = Manifest.permission.ACCESS_FINE_LOCATION
        if (EasyPermissions.hasPermissions(activity, perm)) {
            EasyPermissions.requestPermissions(activity, getString(R.string.rationale_location),
                    RC_REQUEST_LOCATION, perm)
            // TODO this gives warning ===>
            _currentLocation = LocationServices.FusedLocationApi.getLastLocation(_googleApiClient)
        } else {
            //permission denied
        }
    }
```

Thus, IDE offers to add annotation @SuppressLint("MissingPermission") 
or handle security exception.

What is wrong?

**Comment by samtstern** [comment]
@Leonid-Kiev nothing is wrong!  The linter that gives you that warning is just not very sophisticated.  It can only detect a standard permission check (not using EasyPermissions) and the check has to be surrounding the location call.

Suppressing the lint is, unfortunately, the best thing you can do here.
