### ISSUE TITLE
License (Copyright) Owner and Year Information

### ISSUE THREAD

**Issue by berviantoleo** [googlesamples/easypermissions#147]
In [license file](https://github.com/googlesamples/easypermissions/blob/master/LICENSE) the year information and copyright owner not changed. This information should change or replaced to accept the license of Apache 2.0. Who will be copyright owner? I will update the license file and add license section to readme. The year, I will take a first time this repo build.

**Comment by samtstern** [comment]
@berviantoleo that's a good catch!  It should be Google and 2017, do you want to send a pull request?

**Comment by berviantoleo** [comment]
Yes, I will.
