### ISSUE TITLE
A little confuse with @AfterPermissionGranted

### ISSUE THREAD

**Issue by rantianhua** [googlesamples/easypermissions#149]
I have a little confuse to understand `AfterPermissionGranted` annotation. In Readme file, there is a description for it 
> If all of the permissions in a given request are granted, any methods annotated with the proper request code will be executed

So I can believe that the specified permissions have been granted in this annotation, and there is no need to check permissions again. However, it's not the truth in your sample code for `@AfterPermissionGranted`:  
```
@AfterPermissionGranted(RC_CAMERA_AND_LOCATION)
private void methodRequiresTwoPermission() {
    String[] perms = {Manifest.permission.CAMERA, Manifest.permission.ACCESS_FINE_LOCATION};
    if (EasyPermissions.hasPermissions(this, perms)) {
        // Already have permission, do the thing
        // ...
    } else {
        // Do not have permissions, request them now
        EasyPermissions.requestPermissions(this, getString(R.string.camera_and_location_rationale),
                RC_CAMERA_AND_LOCATION, perms);
    }
}
```
In the end, my question is that why needs to check having permissions or not again in method annotated by `AfterPermissionGranted` ?

**Comment by rantianhua** [comment]
@samtstern Sorry to trouble you for your time, but I am really a little hurry!

**Comment by rantianhua** [comment]
After read the code, I have understood!

**Comment by samtstern** [comment]
@rantianhua glad you figured it out!

**Comment by samtstern** [comment]
@quevon24 you have the correct understanding.  Here's the basic flow:

1. call `methodRequiresTwoPermission()`
2. The `if()` check fails, so the `else` branch executes and permissions are requested
3. When the permissions are granted, the method is called again
4. This time, the `if()` check passes and that branch is run

This allows you to keep a single "self-healing" method that requests permissions when it needs them.
