### ISSUE TITLE
onPermissionsGranted isn't been called

### ISSUE THREAD

**Issue by MohamedISoliman** [googlesamples/easypermissions#151]
in camera activity this callback is not been called, this is my code for requesting the camera permission
```

 private void requestCameraPermission() {
    if (EasyPermissions.hasPermissions(this, Manifest.permission.CAMERA)) {
      scanQr();
    } else {
      EasyPermissions.requestPermissions(this, getString(R.string.camera_permission_hint),
          PERMISSION_REQUEST_CODE_CAMERA, Manifest.permission.CAMERA);
    }
  }
``` 
and the activity is extending  AppCompatActivity

**Comment by SUPERCILEX** [comment]
Are you listening for the callback?
https://github.com/googlesamples/easypermissions/blob/master/easypermissions/src/main/java/pub/devrel/easypermissions/EasyPermissions.java#L187-L205

**Comment by MohamedISoliman** [comment]
no I'm only implmented EasyPermissions.PermissionCallbacks in my activity.
```

  @Override public void onPermissionsGranted(int requestCode, List<String> perms) {
    Timber.d("onPermissionsGranted called");
    if (requestCode == PERMISSION_REQUEST_CODE_CAMERA) {
      scanQr();
    }
  }

  @Override public void onPermissionsDenied(int requestCode, List<String> perms) {
    if (requestCode == PERMISSION_REQUEST_CODE_CAMERA) {
      finish();
    }
  }
```

**Comment by SUPERCILEX** [comment]
@MohamedISoliman well have a look at the documentation I posted above, you need to override `onRequestPermissionsResult` and forward that along to EasyPermissions. 😀

**Comment by MohamedISoliman** [comment]
aha my bad then thanks 👍

**Comment by SUPERCILEX** [comment]
No prob!

**Comment by nAkhmedov** [comment]
> @MohamedISoliman well have a look at the documentation I posted above, you need to override `onRequestPermissionsResult` and forward that along to EasyPermissions. 😀

is @AfterPermissionGranted annotated method calling after enable permission in Fragment?

**Comment by ronenfe** [comment]
Thanks, I copy pasted the code from another project and missed copying it:

    override fun onRequestPermissionsResult(requestCode: Int, permissions: Array<String>, grantResults: IntArray) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults)

        // EasyPermissions handles the request result.
        EasyPermissions.onRequestPermissionsResult(requestCode, permissions, grantResults, this)
    }
