### ISSUE TITLE
Android Studio 2.3.3 show SecurityException error when using easypermissions

### ISSUE THREAD

**Issue by xanscale** [googlesamples/easypermissions#155]
All works perfectly but Android Studio show me this error on setMyLocationEnabled

Call requires permission which may be rejected by user: code should explicitly check to see if permission is available (with `checkPermission`) or explicitly handle a potential `SecurityException`

```
@AfterPermissionGranted(RC_LOCATION)
private void setMyLocationEnabled() {
	if (EasyPermissions.hasPermissions(this, Manifest.permission.ACCESS_FINE_LOCATION))
		mMap.setMyLocationEnabled(true);
	else
		EasyPermissions.requestPermissions(this, getString(R.string.accessLocationRational), RC_LOCATION, Manifest.permission.ACCESS_FINE_LOCATION);
}
```

**Comment by samtstern** [comment]
@xanscale unfortunately there's nothing we can do about this, you have to add the comment/annotation to ignore the linter.  Android Studio's permissions linter only looks for calls to the system permissions API and does not know about `EasyPermissions`.

**Comment by xanscale** [comment]
@samtstern yes you are right but inside EasyPermissions you call system permissions API. android lint doesn't analyze code in depth.

same problem exists if use system permissions API in 2 level depth.

Is there a way to report it?


PS the correct annotation is: @SuppressWarnings({"MissingPermission"})

**Comment by samtstern** [comment]
@xanscale you could try reporting it here: https://developer.android.com/studio/report-bugs.html
