### ISSUE TITLE
Fragments request permissions, callback of the activity is triggered

### ISSUE THREAD

**Issue by fly263** [googlesamples/easypermissions#159]
Run the sample,click 'SMS' button,why activity‘s onPermissionsGranted called?Is this right?
this is log：
09-01 14:15:55.371 7396-7396/pub.devrel.easypermissions.sample D/MainFragment: onPermissionsGranted:122:1
09-01 14:15:55.371 7396-7396/pub.devrel.easypermissions.sample D/MainActivity: onPermissionsGranted:65658:1

Android API:24

**Comment by AlphaGao1993** [comment]
I have the same problem, when I request read storage permission in fragment ,only parent activity's on onRequestPermissionsResult was called.

**Comment by saran2020** [comment]
Even I am facing same issue. Did any one happy to find the reason for the same?

**Comment by saran2020** [comment]
For the people who are looking for the solution to this in `onRequestPermissionsResult()` you have to call pass this as receiving, who will be receiving the callbacks.

Like this
`EasyPermissions.onRequestPermissionsResult(requestCode, permissions, grantResults, this);`

**Comment by samtstern** [comment]
@saran2020 thanks for following up with your solution!  Due to lack of any other information I will mark this as closed.

**Comment by fabianTMC** [comment]
I am facing this issue as well on v1.1.3. I am using android.app.Fragment and the callback is running in the Activity. How can I get the callback to run on the Fragment?
