### ISSUE TITLE
I got this compile error

### ISSUE THREAD

**Issue by cheyiliu** [googlesamples/easypermissions#160]
Error:(3610) Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.DayNight.DarkActionBar'.

**Comment by SUPERCILEX** [comment]
@cheyiliu Oh shoot, that would be my fault. As a workaround, you can add this dependency:
https://github.com/googlesamples/easypermissions/blob/25302f5672a851444d74909ac7472db3dffae860/easypermissions/build.gradle#L23

@samtstern Should we make AppCompat an `api` dependency or force devs to add it manually?

**Comment by cheyiliu** [comment]
@SUPERCILEX thanks

**Comment by samtstern** [comment]
@SUPERCILEX we shouldn't force anyone to add it manually, so we should probably change it back to an `api` dependency.

**Comment by SUPERCILEX** [comment]
@samtstern oh well, see #161

**Comment by samtstern** [comment]
@cheyiliu this will be in version 1.0.1 but you can fix it for now by adding a dependency on your app on `appcompat-v7`.

**Comment by bangbing** [comment]
waiting for 1.0.1  ^^@samtstern

**Comment by samtstern** [comment]
Version `1.0.1` has been released.
