### ISSUE TITLE
AppSettingsDialog.Builder can't set clicklistener

### ISSUE THREAD

**Issue by EricMo** [googlesamples/easypermissions#162]
So,AppSettingsDialog.Builder can't set a clicklistener.
Sometimes i want do something when user cancel the AppSettingsDialog,but i can't do this with AppSettingsDialog.

**Comment by SUPERCILEX** [comment]
@EricMo have a look at the documentation:
https://github.com/googlesamples/easypermissions/blob/d1fc87759057dccc1be26e3c314e4f6b28758e1e/easypermissions/src/main/java/pub/devrel/easypermissions/AppSettingsDialog.java#L257 -L264

**Comment by EricMo** [comment]
@SUPERCILEX 
Thx，I find a way to do this.The  documentation:
` @Override
    public void onClick(DialogInterface dialog, int which) {
        if (which == Dialog.BUTTON_POSITIVE) {
            startActivityForResult(
                    new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS)
                            .setData(Uri.fromParts("package", getPackageName(), null)),
                    APP_SETTINGS_RC);
        } else if (which == Dialog.BUTTON_NEGATIVE) {
            setResult(Activity.RESULT_CANCELED);
            finish();
        } else {
            throw new IllegalStateException("Unknown button type: " + which);
        }
    }`
So this is my code:
`@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        //user go to the setting and back
        if (requestCode == AppSettingsDialog.DEFAULT_SETTINGS_REQ_CODE) {
            requestStoragePermission();
        }
        //user don't go to the setting,just cancel the AppSettingsDialog
        if (resultCode == Activity.RESULT_CANCELED) {
            finish();
        }
    }`

**Comment by SUPERCILEX** [comment]
@EricMo Your code should be similar to what I attached but with features. You'll want to do whatever you need to do if you have the permission, otherwise do nothing since the user knows they didn't enable the permission.
https://github.com/googlesamples/easypermissions/blob/d1fc87759057dccc1be26e3c314e4f6b28758e1e/app/src/main/java/pub/devrel/easypermissions/sample/MainActivity.java#L132-L150

**Comment by EricMo** [comment]
@SUPERCILEX Yes,i understand what you say.Your code will be more friendly to user.Thx
