### ISSUE TITLE
Rationale cancel callback

### ISSUE THREAD

**Issue by jdermont** [googlesamples/easypermissions#164]
Sorry if this was already covered, but I couldn't find it anywhere.

```
EasyPermissions.requestPermissions(
    this,
    "You need to grant permissions",
    PERMISSION_REQUEST,
    Manifest.permission.RECORD_AUDIO)
```

Before the actual permissions asking I get dialog with rationale and OK and Cancel buttons. When OK is clicked - it goes to permission asking. If cancel is clicked, dialog dismisses but I can't find any way to set listener for that.

**Comment by samtstern** [comment]
@jdermont if the user cancels the rationale dialog you should get a regular permission denied callback.

**Comment by jdermont** [comment]
@samtstern ok, needed also to make Activity implement EasyPermissions.PermissionCallbacks
