### ISSUE TITLE
How to skip rationale dialog OK/Cancel while requesting permission

### ISSUE THREAD

**Issue by stasbar** [googlesamples/easypermissions#165]
Hello,
How to skip rationale OK/Cancel dialog while requesting permission ?
In my opinion it's quite redundant to ask twice if user want to grand storage permissions, especially when it's in self-described context. 
In other words, is it possible to **EasyPermissions.requestPermissions()** acts like normal **requestPermissions()** but calls **@AfterPermissionGranted** afterwards

**Comment by stasbar** [comment]
Nevermind. Standard **requestPermissions()** calls **@afterpermissiongranted** afterwards by default 😄

**Comment by swetha-thoomoju** [comment]
Hi,
I am facing the same issue mentioned by @thuan09878. When I use standard requestPermissions() not triggering @afterpermissiongranted.  

This is really confusing to ask permission twice. Is there any fix for this?

**Comment by swetha-thoomoju** [comment]
Sorry, Figure it. Standard requestPermissions() is different for Activity and Fragment.

Replaced 
`ActivityCompat.requestPermissions(
        getActivity(),
        new String[]{Manifest.permission.READ_CALENDAR,  Manifest.permission.WRITE_CALENDAR},
        Permissions.CALENDAR_REQUEST_CODE);`

With

`requestPermissions(
                new String[]{Manifest.permission.READ_CALENDAR,  Manifest.permission.WRITE_CALENDAR},
                Permissions.CALENDAR_REQUEST_CODE);`

**Comment by SomnathS09** [comment]
@stanbar got solution?
