### ISSUE TITLE
Caller must be an Activity or a Fragment

### ISSUE THREAD

**Issue by saintjab** [googlesamples/easypermissions#17]
I am using EasyPermission from Fragment but I am getting this error: Caller must be an Activity or a Fragment. Help.

**Comment by samtstern** [comment]
Make sure you are using the support-v4 Fragments and not the Android SDK standard Fragment.

**Comment by saintjab** [comment]
Unfortunately, I am using lots of Android SDK standard Fragment so I can't revert to the support fragment. Any other way to use this library in my current case?

**Comment by samtstern** [comment]
Sorry right now this library only supports the support fragments.

It is generally best practice to use the support fragments and you should be able to drop it in to your application even if it's very complex.  It will be good for your app in the long run and it should not be much work.

**Comment by samtstern** [comment]
@saintjab version 0.1.6 supports android.app.Fragment !
