### ISSUE TITLE
Android6.0 after the code read ANR traces.txt file permissions issue

### ISSUE THREAD

**Issue by wcglws** [googlesamples/easypermissions#171]
Hello, through the code to read ANR exception traces.txt file upload server, but will report the permission of the error, the log did not suggest what permissions. Is not Android6.0 after the permission was recovered?

**Comment by samtstern** [comment]
@wcglws I can't understand what the issue is from your description.  Can you provide some error messages and code that causes the issue?

**Comment by wcglws** [comment]
Unable to open stack trace file '/data/anr/traces.txt': Permission denied while the permission is granted
 I dont know whats wrong with my code below. Can anyone tell me what i need to do.
code:
![code](https://user-images.githubusercontent.com/16982083/31775446-3f535ffe-b51b-11e7-8a73-53d5ee29fca0.jpg)

error:

![error](https://user-images.githubusercontent.com/16982083/31775465-474a2396-b51b-11e7-8bf1-87670a9a543a.jpg)

**Comment by samtstern** [comment]
@wcglws there's no indication that this is an Easypermissions library issue.  Instead this sounds like something that is a problem in your app code.  Please post this question to StackOverflow.
