### ISSUE TITLE
huawei p10  .... error

### ISSUE THREAD

**Issue by Allyns** [googlesamples/easypermissions#172]
Huawei p10 and other models using this library is invalid, unable to pop-up permission application prompt box, the author can test. I also want to know what caused this

**Comment by samtstern** [comment]
@Allyns thanks for filing this issue, but we need more information.

What errors do you get?  What code causes the error?  Anything interesting in the logs?

**Comment by samtstern** [comment]
Closing this issue due to lack of response in 2 weeks.
