### ISSUE TITLE
MIUI  no camera permission but return EasyPermissions.hasPermissions(this, Manifest.permission.CAMERA); return true

### ISSUE THREAD

**Issue by LukeMi** [googlesamples/easypermissions#173]
as the title,can help this ?thanks!

**Comment by samtstern** [comment]
@LukeMi this would happen if the device is running on API < 23 or if there have been OS modifications.  Can you demonstrate that you get a different result using the Android system permissions API?

**Comment by LukeMi** [comment]
@samtstern  sure , Thanks all the same,bro
