### ISSUE TITLE
Allow customization of rationale dialog theme

### ISSUE THREAD

**Issue by rramprasad** [googlesamples/easypermissions#174]
Rationale message dialog shows text and buttons as white color.Actually my app needs colorAccent should be white.So not able to set custom theme for rationale dialog.How to fix this issue.

**Comment by lingdianguole** [comment]
me too,How to fix this issue for you

**Comment by jrm0695** [comment]
how to even disable the rationale message ? i need to make my own behavior when the user deny a permission without having to deal with this dialog

**Comment by rramprasad** [comment]
For workaround,I have changed my colorAccent for the particular Activity by setting separate theme.But we need to make the rationale message as optional and theme customization

**Comment by samtstern** [comment]
As @rramprasad this color comes from `colorAccent`.

**Comment by samtstern** [comment]
This has been fixed by @SUPERCILEX and is available in version `1.1.0` through the new `PermissionRequest` API.  See the `README` for details.
