### ISSUE TITLE
Failed to resolve: pub.devrel:easypermissions:1.1.1

### ISSUE THREAD

**Issue by xinpengfei520** [googlesamples/easypermissions#181]
## Basic Information

Device type: ____xiaomi 5____
OS version: ______7.0__
EasyPermissions version: ______1.1.1__

## Describe the problem

Failed to resolve: pub.devrel:easypermissions:1.1.1

What happened?  What did you expect to happen?

gradle cant't build

## Code and logs

Error:(106, 20) Failed to resolve: pub.devrel:easypermissions:1.1.1 <a href=

```
// TODO(you): show the code that produces the problem,
//            and any relevant logs.
```

**Comment by samtstern** [comment]
The latest version is 1.1.0 ... Maybe I made a typo in the docs?  1.1.1
should not exist.

**Comment by xinpengfei520** [comment]
Thank you , I will try it.

**Comment by fdh19979** [comment]
you can use 1.1.0 , it work on me

**Comment by meetr-spaceo** [comment]
Failed to resolve :  pub.devrel:easypermissions:1.1.1
