### ISSUE TITLE
could add an arguments in RequestPermissions

### ISSUE THREAD

**Issue by fdh19979** [googlesamples/easypermissions#182]
## Basic Information

Device type: ________
OS version: ___7.0_____
EasyPermissions version: ___1.1.0_____

## Describe the problem

when i use "EasyPermissions.requestPermissions" , if user denied this request before , a dialog will be showed anyway.

Counld add a new arguments for this method to control whether to show this dialog ? 

## Code and logs

```
// TODO(you): show the code that produces the problem,
//            and any relevant logs.
```

**Comment by SUPERCILEX** [comment]
I can't reproduce that issue... On what device is it happening?

**Comment by samtstern** [comment]
@fdh19979 due to a lack of response for ~4 weeks I am going to close this issue.  If you do have more information please comment and I will re open.
