### ISSUE TITLE
EasyPermissions.requestPermissions() not showing dialog in google sample app

### ISSUE THREAD

**Issue by petercutting** [googlesamples/easypermissions#183]
Device type: _LG G6
OS version: __M
EasyPermissions version: _1.1.0

I am testing the sample app:- 
https://developers.google.com/gmail/api/quickstart/android    which uses credentials to access gmail

pressing button "CALL GMAIL API" results in a call to EasyPermissions.requestPermissions() but no dialog appears on the screen

            EasyPermissions.requestPermissions(
                    this,
                    "This app needs to access your Google account (via Contacts).",
                    REQUEST_PERMISSION_GET_ACCOUNTS,
                    Manifest.permission.GET_ACCOUNTS);
        }

**Comment by petercutting** [comment]
I had forgotten to include in manifest:-
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />

**Comment by samtstern** [comment]
The page you linked to references `compile 'pub.devrel:easypermissions:0.3.0'` but your issue says `1.1.0`.  Did you manually change the version?

**Comment by petercutting** [comment]
Yes I did change it manually cos I couldn't get it to work (my mistake).
First I found a ref to 1.1.1 on the interwebs . Eventually realised that it
doesn't exist and tried 1.1.0. then found my permissions XML bug. Working
now


Peter Cutting
work    +46 40 105858 (ring this number)
work    +46 705 505806 (SMS)
private +46 708 565056 (maybe)

**Comment by samtstern** [comment]
@petercutting glad it's working for you now!  And I fixed the reference to `1.1.1` to say `1.1.0`, that was my mistake.
