### ISSUE TITLE
Cannot resolve PermissionRequest

### ISSUE THREAD

**Issue by xomnot** [googlesamples/easypermissions#186]
## Basic Information

Device type: ________
OS version: ________
EasyPermissions version: ____1.0.1____

## Describe the problem

I'm trying to use a PermissionRequest to control the rationale dialog, as mentioned on README:

`EasyPermissions.requestPermissions(
        new PermissionRequest.Builder(this, RC_CAMERA_AND_LOCATION, perms)
                .setRationale(R.string.camera_and_location_rationale)
                .setPositiveButtonText(R.string.rationale_ask_ok)
                .setNegativeButtonText(R.string.rationale_ask_cancel)
                .setTheme(R.style.my_fancy_style)
                .build());`

But I get **cannot resolve PermissionRequest**

Android Studio suggests me to import android.webkit.PermissionRequest but this is obviously not working.

**Comment by samtstern** [comment]
@xomnot you need to use EasyPermissions version `1.1.0` or higher.

**Comment by xomnot** [comment]
Ouch! Version numbers were so similar...
