### ISSUE TITLE
Can not be fixed support version

### ISSUE THREAD

**Issue by gedoor** [googlesamples/easypermissions#189]
All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.0.1, 26.1.0. Examples include com.android.support:animated-vector-drawable:27.0.1 and com.android.support:cardview-v7:26.1.0 less... (Ctrl+F1) 
There are some combinations of libraries, or tools and libraries, that are incompatible, or can lead to bugs. One such incompatibility is compiling with a version of the Android support libraries that is not the latest version (or in particular, a version lower than your targetSdkVersion.)

**Comment by samtstern** [comment]
@gedoor add the following dependencies to your app:

```
    implementation "com.android.support:appcompat-v7:27.0.1"
    implementation "com.android.support:support-compat:27.0.1"
    implementation "com.android.support:support-fragment:27.0.1"
```

**Comment by umarhussain15** [comment]
Please add this in the setup instructions as well, because without these dependencies, the layout of the app is disturbed and text in the appbar has not correct style.
