### ISSUE TITLE
Don't require permissions callbacks

### ISSUE THREAD

**Issue by samtstern** [googlesamples/easypermissions#19]
Using only annotations to receive permission results is valid in some simple use cases.

**Comment by jaibatrik** [comment]
If the requirement for the callbacks are removed, we can have more intuitive overloads of `requestPermissions` accepting either `Activity` or `Fragment` as the first argument.

**Comment by samtstern** [comment]
@jaibatrik yep that would be nice.  I keep putting this task off as other things come up, if you have time and want to submit a PR I'd be happy to review.

**Comment by jaibatrik** [comment]
Sure, looking into it :)

**Comment by jaibatrik** [comment]
@samtstern Do we have any plans on how to go about this?

The simplest way would be to not change the signature of the `requestPermissions` method and still allow it to accept an `Object`. Then we can just skip the calls to `onPermissionsGranted` and `onPermissionsDenied` if the `Object` is not an instance of `PermissionCallbacks` and just call `runAnnotatedMethods`. 

The document needs to updated substantially to make it clear that the `PermissionCallbacks` are optional indeed.

**Comment by samtstern** [comment]
@jaibatrik that sounds like a pretty good plan.  The key thing is not to break existing API calls or behavior, updating the documentation to say that the callbacks are optional should not be too hard.

**Comment by samtstern** [comment]
Fixed by #31
