### ISSUE TITLE
Crash when deny permission #184 

### ISSUE THREAD

**Issue by guominfang** [googlesamples/easypermissions#190]
My English is poor, this paper is from youdao translation,I hope you can understand.

## Basic Information

Device type: MI 5
OS version:  7.0
EasyPermissions version: 1.1.1

## Describe the problem

The situation is the same as #184 

## Code and logs

![image](https://user-images.githubusercontent.com/24568042/34345335-13b33534-ea29-11e7-8483-ce2fd7f801aa.png)
![image](https://user-images.githubusercontent.com/24568042/34345595-2a38ea0e-ea2b-11e7-897b-75419950b802.png)

I don't seem to have the wrong information
![image](https://user-images.githubusercontent.com/24568042/34345898-8c0d74be-ea2d-11e7-8a0c-3bdd48abe24d.png)

##  If you request permissions like this, the software does not crash
![image](https://user-images.githubusercontent.com/24568042/34346307-3fa84ec4-ea31-11e7-8876-769e905fbebe.png)
There is no need to limit **compileSdkVersion** or **targetSdkVersion** or **buildToolsVersion** or **support libs verion**

## Idea
Hope EasyPermissions,  Can be integrated This method,Only request not get permissions.

**Comment by samtstern** [comment]
@guominfang can you show what the crash is?

**Comment by guominfang** [comment]
Just like #184 described it.

**Comment by samtstern** [comment]
@guominfang yes but we consider #184 to be fixed.  Is there something different about your situation?  Have you tried all the solutions in that thread?

**Comment by guominfang** [comment]
Yes, I did.
easypermissions 1.1.1  
compileSdkVersion 27
supportVersion = '27.0.2'
buildToolsVersion = '27.0.2'

##  Request Multitude Permissions 
Request Permissions button -> Deny first permission, **Grant the second permission**
Request Permissions button again -> Deny first permission, **Deny the second permission** -> Crash (Application is restarted)

### The reason for the collapse was the rejection of the permission granted last time.

## My solution :   
The permission that has been obtained is not requested.
![image](https://user-images.githubusercontent.com/24568042/34346307-3fa84ec4-ea31-11e7-8876-769e905fbebe.png)

**Comment by SUPERCILEX** [comment]
I don't see why what you're doing wouldn't work, but it's bad UX anyway. You should be asking for the permissions at the same time like so:
```java
String[] perms = new String[] {
        Manifest.permission.CAMERA,
        Manifest.permission.WRITE_EXTERNAL_STORAGE
};
if (EasyPermissions.hasPermissions(this, perms)) {
    saveImage();
} else {
    EasyPermissions.requestPermissions(this, "...", code, perms);
}
```

Let us know if that helps! 😄

**Comment by guominfang** [comment]
@SUPERCILEX   
## Is it ok if you use it this step?

### Step 1:
Request Permissions button -> Deny first permission, Grant the second permission

### Step 2:
Request Permissions button again -> Deny first permission, Deny the second permission -> Crash (Application is restarted)

**Comment by samtstern** [comment]
@guominfang is this issue happening in an open-source repo that I could clone and try?

**Comment by guominfang** [comment]
@samtstern of course， I created demo
[EasypermissionsDemo](https://github.com/guominfang/EasypermissionsDemo)

**Comment by samtstern** [comment]
@guominfang thank you for making the demo.  I have tried to reproduce using your demo but it does not crash on my device.  See the video here:
https://drive.google.com/file/d/1zawXJ2tgJ3ejO3MvWEcWFMGs1cM0zDoY/view?usp=sharing

**Comment by guominfang** [comment]
@samtstern Thank you. I know where our differences are.When the permission button is requested again,Your phone will no longer pop up the authorized dialog box.But my phone will still pop up the permission dialog box.
It could be that Chinese handset maker xiaomi has customized the android system.
[Please look at this video : https://github.com/guominfang/EasypermissionsDemo/blob/master/53dc4a975a06684543f2b8c5f735d9af.mp4](https://github.com/guominfang/EasypermissionsDemo/blob/master/53dc4a975a06684543f2b8c5f735d9af.mp4)

**Comment by guominfang** [comment]
@samtstern Without changing the easypermissions source code, my approach is：
```
private void checkPerm() {
        List<String> strings = new ArrayList<>();
        if (!EasyPermissions.hasPermissions(this, Manifest.permission.WRITE_EXTERNAL_STORAGE)) {
            strings.add(Manifest.permission.WRITE_EXTERNAL_STORAGE);
        }

        if (!EasyPermissions.hasPermissions(this, Manifest.permission.CAMERA)) {
            strings.add(Manifest.permission.CAMERA);
        }
        String[] params =  strings.toArray(new String[strings.size()]);

        if (EasyPermissions.hasPermissions(this, params)) {
            saveImage();
        } else {
            EasyPermissions.requestPermissions(this, "需要相机和读写本地权限", WRITE_EXTERNAL_STORAGE, params);
        }
    }
```

So, There is no need to limit compileSdkVersion 27 or targetSdkVersion  27 or buildToolsVersion 27.0.1 or support libs verion 27.0.1

**Comment by samtstern** [comment]
@guominfang does that mean you consider this issue fixed?

**Comment by guominfang** [comment]
@samtstern Yes, I think so.It would be better if the easypermissions itself could support this adaptation.

**Comment by Pinggo** [comment]
Request Permissions button -> Deny first permission, Grant the second permission

Request Permissions button again -> Deny first permission, Deny the second permission -> Crash (Application is restarted)
I also find this problem,your solution works fine.Thank you!
