### ISSUE TITLE
EasyPermissions.requestPermissions拒绝后无法再弹出来

### ISSUE THREAD

**Issue by danniu1314** [googlesamples/easypermissions#191]
## Basic Information

Device type: __红米NOTE 4X______
OS version: ___MIUI 8 7.5.11_____
EasyPermissions version: __1.1.1_____

## Describe the problem

拒绝权限后，第二次再检测权限无反应，不弹出dialog提示，

## Code and logs

```
// TODO(you): show the code that produces the problem,
//            and any relevant logs.
```

**Comment by samtstern** [comment]
@danniu1314 I apologize but I can only help with issues in English.  Please file a new issue or try a different forum that can help in another language!

**Comment by KevinChang007** [comment]
above means that: 
if the permissions are refused, the tips dialog can't be popped out when I request these permissions the second time.

Device type: Red NOTE 4X 
OS version: MIUI 8 7.5.11
EasyPermissions version: 1.1.1
