### ISSUE TITLE
Easypermissions in kotlin

### ISSUE THREAD

**Issue by Joslyn-Chen** [googlesamples/easypermissions#197]
## Basic Information

Device type: Android Emulator
OS version: 8.0
EasyPermissions version: 1.1.2

## Describe the problem

Apply for multiple permissions.
Method EasyPermissions.requestPermissions() last parameter,I use arrayOf not passed.
How to pass this parameter in kotlin?

**Comment by samtstern** [comment]
@Joslyn-Chen can you show the code you're writing (in Kotlin) so I can better understand the problem>

**Comment by Joslyn-Chen** [comment]
@samtstern Yes.
`
private val perms = arrayOf(
      Manifest.permission.ACCESS_FINE_LOCATION,
      Manifest.permission.WRITE_EXTERNAL_STORAGE,
      Manifest.permission.CALL_PHONE)

  private fun getPermissions() {
    if (!EasyPermissions.hasPermissions(this, perms)) {
      EasyPermissions.requestPermissions(this, "", 0,
          Manifest.permission.ACCESS_FINE_LOCATION)
    }
    if (!EasyPermissions.hasPermissions(this, Manifest.permission.WRITE_EXTERNAL_STORAGE)) {
      EasyPermissions.requestPermissions(this, "", 0,
          Manifest.permission.WRITE_EXTERNAL_STORAGE)
    }
    if (!EasyPermissions.hasPermissions(this, Manifest.permission.CALL_PHONE)) {
      EasyPermissions.requestPermissions(this, "", 0,
          Manifest.permission.CALL_PHONE)
    }
  }
`
`EasyPermissions.hasPermissions(this, perms)` error

**Comment by SUPERCILEX** [comment]
@Joslyn-Chen Kotlin has a special syntax for spreading an array into a varargs parameter: `*perms`.

**Comment by Joslyn-Chen** [comment]
@SUPERCILEX Thank you very much.

**Comment by samtstern** [comment]
Looks like @SUPERCILEX solved it, thanks!

**Comment by yizuochengchi** [comment]
thanks！ 😀every one

**Comment by ngallazzi** [comment]
Thanks!!

**Comment by nurhidayat507** [comment]
Thanksss :D
