### ISSUE TITLE
Fragment can't receive onRequestPermissionsResult after showing RationaleDialog

### ISSUE THREAD

**Issue by b95505017** [googlesamples/easypermissions#198]
If we call `EasyPermissions.requestPermissions` from Fragment and show rational dialog:

```java
    @Override
    public void showRequestPermissionRationale(@NonNull String rationale,
                                               @NonNull String positiveButton,
                                               @NonNull String negativeButton,
                                               @StyleRes int theme,
                                               int requestCode,
                                               @NonNull String... perms) {

        FragmentManager fm = getSupportFragmentManager();
```
https://github.com/googlesamples/easypermissions/blob/master/easypermissions/src/main/java/pub/devrel/easypermissions/helper/BaseSupportPermissionsHelper.java#L32

```java
    @Override
    public FragmentManager getSupportFragmentManager() {
        FragmentActivity hostActivity = getHost().getActivity();
        if (hostActivity != null) {
            return hostActivity.getSupportFragmentManager();
        } else {
            return getHost().getChildFragmentManager();
        }
    }
```

This will return hostActivity.getSupportFragmentManager(), causing request permissions using `ActivityCompat.requestPermissions(xxx)`, this way the host fragment can't receive `onRequestPermissionsResult`, only its host Activity.

**Comment by SUPERCILEX** [comment]
Ouch! That completely slipped my mind, sorry @samtstern. 😊 @b95505017 this should be fixed soon.

**Comment by samtstern** [comment]
@b95505017 thanks for raising this and @SUPERCILEX thanks for the quick fix!

**Comment by b95505017** [comment]
Thanks for your help!

**Comment by samtstern** [comment]
@b95505017 I will put out a release that includes this fix soon.

**Comment by samtstern** [comment]
Released `3.1.3`.

**Comment by b95505017** [comment]
@samtstern Should be `1.1.3`, thanks!

**Comment by samtstern** [comment]
Oops yeah!
