### ISSUE TITLE
Methods not executing

### ISSUE THREAD

**Issue by seang96** [googlesamples/easypermissions#20]
Any method with @AfterPermissionGranted annotation is not executed and the overriden methods onRequestPermissionsResult, onPermissionsGranted, and onPermissionsDenied do not execute for me. I implemented the class inside of a fragment class. I have tried to make the method with the annotation publc and private, both failed. 

The permission does get granted/denied so it seems to be partially working for me. I would like to get the code executed soon as the permissions are granted working though.

**Comment by samtstern** [comment]
@seang96 are you calling `EasyPermissions.onRequestPermissionsResult` in your Fragment?

**Comment by samtstern** [comment]
Also make sure you always call `super.onRequestPermissionsResult(requestCode, permissions, grantResults);` whenever you Override it

**Comment by seang96** [comment]
Yeah, the method has both of those in there. I Implemented the class, I also tried @AfterPermissionGranted in the method that checks/requests/and handles what to do if the check succeeds, which only calls when I first check it.

`    @AfterPermissionGranted(RC_FINE_LOCATION)
    public void locationPermissions() {
        String perm = Manifest.permission.ACCESS_FINE_LOCATION;
        if (EasyPermissions.hasPermissions(getContext(), perm)) {
            googleMap.getUiSettings().setMyLocationButtonEnabled(true);
            googleMap.setMyLocationEnabled(true);
        } else {
            EasyPermissions.requestPermissions(getContext(), "Would you like your location displayed with the bus route?", RC_FINE_LOCATION, perm);
        }
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);

        // Forward results to EasyPermissions
        EasyPermissions.onRequestPermissionsResult(requestCode, permissions, grantResults, this);
    }

    @Override
    public void onPermissionsGranted(int requestCode, List<String> perms) {
        Log.i("mapFragment", "onPermissionsGranted:" + requestCode + ":" + perms.size());
    }

    @Override
    public void onPermissionsDenied(int requestCode, List<String> perms) {
        Log.i("mapFragment", "onPermissionsDenied:" + requestCode + ":" + perms.size());
    }`

**Comment by samtstern** [comment]
Where you have `requestPermissions(getContext(), ...` can you try replacing it with `requestPermissions(this, ...)` so that the object requesting the permissions is the `Fragment`?

**Comment by seang96** [comment]
Oh well, that worked. Was getContext() causing the method to be sent to the activity that the fragment is running in instead of the method inside of the fragment itself? Thanks for the fix.

**Comment by samtstern** [comment]
Yeah returning results of permissions or startActivity calls to Fragments
relies on some interesting hacks that put the Fragment ID in the request
code.  But if the calling context is not a Fragment the system doesn't know
to do that.

**Comment by nAkhmedov** [comment]
I missed the last param so that i didn't receive @AfterPermissionGranted method calling
replace your code from
`        EasyPermissions.onRequestPermissionsResult(requestCode, permissions, grantResults);
`
to
`        EasyPermissions.onRequestPermissionsResult(requestCode, permissions, grantResults, this);
`
