### ISSUE TITLE
Skip first rational dialog 

### ISSUE THREAD

**Issue by caramelWaffle** [googlesamples/easypermissions#203]
Is it possible to disable rational dialog eg."This app may not work correctly without requested permissions" or remove setRationale(rationale) before building the dialog.

BR.

**Comment by samtstern** [comment]
@caramelWaffle no sorry, there is not.  This library is meant to implement the UX recommendations of the Android platform for permissions.  We don't allow skipping any part of the flow, even though I can understand how you might want that in certain situations.

The best thing to do is probably just use the standard platform permissions API to implement your custom flow.

**Comment by hiftikha** [comment]
this isn't helpful, especially when library is integrated thoroughly with the rest of the app and we're trying to experiment with new custom flows
