### ISSUE TITLE
Manifest.READ_SMS permission issue.

### ISSUE THREAD

**Issue by Rajeshtechgeek** [googlesamples/easypermissions#205]
## Basic Information

Device type: Zenfone3
OS version: Android 8.0
EasyPermissions version: 1.1.3

## Describe the problem
I have both Manifest.READ_SMS,Manifest.RECEIVE_SMS in the Manifest.xml.
I have requested only Manifest.READ_SMS in request permissions from fragment.

My sms broadcast receiver working fine in prior to Oreo devices. But in Oreo device
it's not working.

**Comment by samtstern** [comment]
@Rajeshtechgeek what makes you think this is an issue with EasyPermissions rather than something that has changed in Android Oreo that affects how you're using the SMS APIs?  Can you show some piece of EasyPermissions code that is not working as expected?

**Comment by Rajeshtechgeek** [comment]
The below code is enough for app which is working fine for oreo also.
`   private void requestReadAndSendSmsPermission() {
        if (ActivityCompat.shouldShowRequestPermissionRationale(MainActivity.this, Manifest.permission.READ_SMS)) {
            Log.d(TAG, "shouldShowRequestPermissionRationale(), no permission requested");
            return;
        }
        ActivityCompat.requestPermissions(MainActivity.this, new String[]{Manifest.permission.READ_SMS},
                SMS_PERMISSION_CODE);
    }`
This is what me think there may be problem in easypermissions. and moreover i know oreo changes about SMS peremissions.

**Comment by Rajeshtechgeek** [comment]
When i did clean project in android studio Even above code stopped to working . There was a gradle build issue in android studio which made me to suspect easy permissions.Thanks!
