### ISSUE TITLE
if user descline info dialog onRequestPermissionsResult not called

### ISSUE THREAD

**Issue by mohamadk** [googlesamples/easypermissions#207]
It's a logical bug.
imagine this scenario that I want to read incoming sms to verify user phone number.
if I send my request to the server then ask for SMS permission, SMS coming to user phone before user answer the permission dialog. so its wrong way to do.
so I should first request for user permission then after user answer that I send my request to the server.but  I cannot get user response if the user dismisses inform dialog. I think this time too onRequestPermissionsResult most called.

**Comment by samtstern** [comment]
@mohamadk the "rationale" dialog is not a request for permissions.  It's a request to ask the user for permissions.  Therefore it would be incorrect to trigger the `onRequestPermissionsResult` callback after the user dismisses this dialog.

I understand your confusion, but there is nothing we can do in this case.
