### ISSUE TITLE
Unable to give SMS permission on xiaomi Note 4

### ISSUE THREAD

**Issue by ankitgupshup** [googlesamples/easypermissions#211]
## Basic Information

Device type: xiaomi note 4
OS version: Nougat[16]
EasyPermissions version: 1.1.3

## Describe the problem
Unable to give SMS read permission.
What happened?  What did you expect to happen?
I have installed the my application on above mentioned mobile. After giving the read SMS permission unable to read SMS from above mentioned mobile. Same code is working fine in all other mobiles except Xiaomi mobiles.
## Code and logs

```
// TODO(you): show the code that produces the problem,
//            and any relevant logs.
```

**Comment by daidaishuiping** [comment]
Error:Gradle DSL method not found: 'implementation()'

**Comment by samtstern** [comment]
@ankitgupshup in your original bug report you say `Nougat[16]` but those are not the same.  Is it running Android N or Android API 16 (which is very old).

Also what exactly is wrong?

- Is the permission never requested?
- Does `hasPermission` never return true?
- Does `hasPermission` return true but the SMS APIs dont work?

**Comment by samtstern** [comment]
Closing this issue because it's old with no response.
