### ISSUE TITLE
0.4.0版本不能申请REQUEST_INSTALL_PACKAGES 应用安装未知程序应用的权限

### ISSUE THREAD

**Issue by liudaohong** [googlesamples/easypermissions#213]
## Basic Information

Device type: ________
OS version: ________
EasyPermissions version: ________

## Describe the problem

What happened?  What did you expect to happen?

## Code and logs

```
// TODO(you): show the code that produces the problem,
//            and any relevant logs.
```

**Comment by samtstern** [comment]
@liudaohong I apologize but I can only support issues filed in english and with complete information.  If you're having trouble and can't meet those requirements please try StackOverflow or similar!

**Comment by hebiao6446** [comment]
REQUEST_INSTALL_PACKAGES   &   READ_LOGS   request permission fail !!!!!!

Device type: HUAWEI MATE 10 PRO 
OS version:  emui 10.0.0  android 10
EasyPermissions version:   pub.devrel:easypermissions:3.0.0

YES,   useAndroidX = true
