### ISSUE TITLE
Version conflict with support lib version 27.1.1

### ISSUE THREAD

**Issue by Naresh-Katta** [googlesamples/easypermissions#217]
When I use this library with support library version 27.1.1, I'm getting error briefly version conflict with 27.1.0.

Where can I tweak to get it fixed?

**Comment by samtstern** [comment]
@Naresh-Katta can you show the `dependencies` block of your `build.gradle`?

**Comment by Naresh-Katta** [comment]
api "com.android.support:appcompat-v7:${suprtLibVrtn}"
    api "com.android.support:design:${suprtLibVrtn}"
    api "com.android.support:recyclerview-v7:${suprtLibVrtn}"
    api "com.android.support:cardview-v7:${suprtLibVrtn}"
    api 'pub.devrel:easypermissions:1.2.0'
    and
    ext {
        suprtLibVrtn = "27.1.0"
    }

**Comment by samtstern** [comment]
@Naresh-Katta try adding dependencies on `support-compat` and `support-fragment` as well.

**Comment by Naresh-Katta** [comment]
All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.1.1, 27.1.0. Examples include 
    com. android. support : animated-vector-drawable:27.1.1 and com.android. support : exifinterface:27.1.0 more... (Ctrl+ F1) 
Still getting the issue.

**Comment by emaborsa** [comment]
Same issue here. Using the 27.1.0 it works, setting 27.1.1 I get the same error.

**Comment by samtstern** [comment]
These are the libraries we depend on:

```
    api "com.android.support:appcompat-v7:$support_library_version"
    api "com.android.support:support-compat:$support_library_version"
    api "com.android.support:support-fragment:$support_library_version"
```

You should add explicit dependencies on each of those at whatever version you want.  That will tell gradle what to do.

Any further problem is coming from another dependency or from your build customizations.

**Comment by emaborsa** [comment]
I took my dependencies, put it into an empty project and 'played' with them, in order to figure out the problem.
In my case it was 'com.squareup.picasso:picasso:2.71828' to conflict with 'com.android.support:appcompat-v7:27.1.1'. By removing it, it works.

**Comment by nareshkatta99** [comment]
@emaborsa is right. This issue not because of easypermissions.
adding `api "com.android.support:exifinterface:27.1.1";` worked like a charm for me
