### ISSUE TITLE
Conductor Controller Integration

### ISSUE THREAD

**Issue by adin234** [googlesamples/easypermissions#225]
Right now, this library only works with activities and fragments, are there any plans to support [Conductor](https://github.com/bluelinelabs/Conductor/)'s Controllers?

**Comment by samtstern** [comment]
@adin234 thanks for the link, I had not heard of the Conductor framework before.  EasyPermissions is just meant to be a wrapper over the Android Framework permissions APIs, we don't plan to support every app architecture directly.

It's not possible to make a permissions request without somehow getting hold of an `Activity` or `Fragment` reference, even if you're using a `View` based framework.

As this is not currently our goal I'm going to close this issue, hope that makes sense!

**Comment by SUPERCILEX** [comment]
Agreed. If you really need to use EP from Conductor, you could always add this hack: `(Activity) view.getContext()`
