### ISSUE TITLE
Issue While creating signed apk

### ISSUE THREAD

**Issue by PbPguna** [googlesamples/easypermissions#229]
## Basic Information
i am using easypermissions1.2.0. while i am creating  signed apk i got

Error:Execution failed for task ':app:transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/common/annotations/Beta.class

this error help me to solve the issue.

**Comment by samtstern** [comment]
`duplicate entry: com/google/common/annotations/Beta.class` that doesn't seem like it has anything to do with EasyPermissions in particular.  Could you try posting this on StackOverflow? That's a better place for general app debugging.
