### ISSUE TITLE
Passing flags to the Intent created from AppSettingsDialog

### ISSUE THREAD

**Issue by sebkur** [googlesamples/easypermissions#230]
## Basic Information

EasyPermissions version: 1.2.0

## Describe the problem

When the user denies a permission request, I'm using an `AppSettingsDialog` in my `onPermissionsDenied()` callback to display a rationale and send the user to the app info screen.
I'm having logic elsewhere in my apps to send the user to the app info screen and would like that behavior to be consistent in terms of the flags passed to the `Intent`. In my case I'm using 

     intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);

to display the app info screen because I think it can confuse users to have app info screen integrated into the app task. I'm not sure who else agrees to that opinion, but maybe you agree that it is desirable to let the developer configure the behavior of the resulting `Intent`.

I think I would implement this by:
* adding a `setIntentFlags(int)` to the `AppSettingsDialog.Builder` class,
* storing the flags in the `AppSettingsDialog`,
* extracting the flags from `AppSettingsDialog` in `AppSettingsDialogHolderActivity`'s `onCreate()`,
* applying the flags to the `Intent` in `AppSettingsDialogHolderActivity`'s `onClick()`
 

What do you think? Is it worth a pull request, are you interested in integrating such a change?

Thanks,
Sebastian

**Comment by samtstern** [comment]
Thanks for the interesting proposal!  What other flags do you think people would be interested in adding to the intent?  If just the one, we could do a more friendly change like adding an openInNewTask() method to the builder.

**Comment by sebkur** [comment]
I'm not sure because there are so many flags and I'm not fully aware of what they're all good for. I've seen people using `FLAG_ACTIVITY_NO_HISTORY` and `FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS` on it, for example in this SO post: https://stackoverflow.com/a/32822298/1268759

**Comment by samtstern** [comment]
This is fixed by #237.

I will release this as `1.3.0` as it's a new feature.

**Comment by sebkur** [comment]
Thanks, looking forward to the release
