### ISSUE TITLE
Is it bug?

### ISSUE THREAD

**Issue by AnMokoto** [googlesamples/easypermissions#231]
## Basic Information

Device type: ___vivo x20_____
OS version: ___7.1.1_____
EasyPermissions version: ___1.2.0_____

## Describe the problem

What happened?  What did you expect to happen?

## Code and logs

```
// TODO(you): show the code that produces the problem,
//            and any relevant logs.
```

![qq 20180727151318](https://user-images.githubusercontent.com/10859832/43307114-ef4c2f8c-91af-11e8-8891-512ffa8d84e6.png)

support version 27.1.1
as verson: 3.1.2

@samtstern i need u help.

**Comment by samtstern** [comment]
@AnMokoto there's not enough information here to debug, you haven't shown the full stack trace or the code that causes the issue.

**Comment by AnMokoto** [comment]
@samtstern  thx for u reply

that's my code below:

```java

public abstract class BasePermissionActivity extends RxAppCompatActivity implements EasyPermissions.PermissionCallbacks {

    private static final int BASE_PERMISSION = 0x1001;

    private static final String[] PERMISSION = {
            Manifest.permission.WRITE_EXTERNAL_STORAGE,
            Manifest.permission.READ_EXTERNAL_STORAGE,
            Manifest.permission.CAMERA,
            Manifest.permission.VIBRATE,
            Manifest.permission.WAKE_LOCK,
            Manifest.permission.MOUNT_UNMOUNT_FILESYSTEMS,
    };

    @Override
    protected void onStart() {
        super.onStart();
        onRequestPermission();
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions,
                                           @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        EasyPermissions.onRequestPermissionsResult(requestCode, permissions, grantResults, this);
    }

    @AfterPermissionGranted(BASE_PERMISSION)
    public void onRequestPermission() {
        if (!EasyPermissions.hasPermissions(this, PERMISSION)) {
            EasyPermissions.requestPermissions(this, getString(R.string.app_permission), BASE_PERMISSION,
                    PERMISSION);
        }
    }

    @Override
    public void onPermissionsGranted(int requestCode, @NonNull List<String> perms) {

    }


    @Override
    public void onPermissionsDenied(int requestCode, @NonNull List<String> perms) {
        if (!EasyPermissions.somePermissionPermanentlyDenied(this, perms)) {
            new AppSettingsDialog.Builder(this).build().show();
        }
    }
}

```

Not of all have reported this error. The log shows that only this Chinese-produced such as `vivo` reported this error.I think of the wrong that `Manifest.permission.MOUNT_UNMOUNT_FILESYSTEMS` even though it's not a native ROM.

**Comment by samtstern** [comment]
@AnMokoto ok it looks like it's getting into an infinite loop.  `hasPermissions` is returning false but then `requestPermissions` is coming back successful immediately.  This calls the annotated method which gets back into the loop.

I assume this only reproduces on certain devices?

**Comment by AnMokoto** [comment]
@samtstern Yeap,it was successfully on the other devices. I did not  known it was makes a fault that the producers does what. Cause the systems were not an Android Native Rom and framework.
i hope u no what i mean. 😢

**Comment by samtstern** [comment]
@AnMokoto I understand.  Unfortunately with device-specific things like this there is nothing we can do in `EasyPermissions`.  The error is at a lower level.

You will need to use the Android system permissions API yourself and track when you get a successful result to avoid getting into a loop, as I think `hasPermissions` is going to lie to you :-/

**Comment by AnMokoto** [comment]
@samtstern   :smile: Thx for u help and I has been fixed this issue yesterday.
