### ISSUE TITLE
Support for compileSdkVersion 28

### ISSUE THREAD

**Issue by gustawdaniel** [googlesamples/easypermissions#233]
## Basic Information

Device type: Moto Z
OS version: Android 8.0
EasyPermissions version: 1.2.0

## Describe the problem

In docs there is written that `compileSdkVersion` should be 27. 

Is it planned update to 28?

I new in Android world, so If my question is inappropriate please explain why or at least link docs. Thank you in advance.

**Comment by SUPERCILEX** [comment]
You're free to update to API 28. But yeah, we need to kill framework fragment support and update to support lib v28 when that hits stable.

**Comment by gustawdaniel** [comment]
Anyway in my case I could not use this library because of error

> https://github.com/googlesamples/easypermissions/issues/231

But this issue can be closed.
