### ISSUE TITLE
EasyPermissions.requestPermissions  How to request the permission directly without pop up the tip message.

### ISSUE THREAD

**Issue by IT-Talon** [googlesamples/easypermissions#235]
## Basic Information

Device type: ___Oneplus 6_____
OS version: _____8.1.0___
EasyPermissions version: ___1.2.0_____

## Describe the problem

What happened?  What did you expect to happen?

I reject the permission request first,then I request the permission again,it will pop up a tip message then the request permission box of the system. I just want it to request the system permission directly without poping up the tip message,what should I do?

## Code and logs

```  EasyPermissions.requestPermissions(context, tip, requestCode, perms);

// TODO(you): show the code that produces the problem,
//            and any relevant logs.
```

**Comment by samtstern** [comment]
@IT-Talon that pop up box is called "rationale" and it is recommended (strongly) by Android UX guidelines. The goal of this library is to make following those guidelines really easy.  If you want to do something else, EasyPermissions is not for you!
