### ISSUE TITLE
Make permission rationale survive rotation

### ISSUE THREAD

**Issue by samtstern** [googlesamples/easypermissions#24]
If the user rotates while the rationale request is up, we leak the dialog and the request is lost

**Comment by k0shk0sh** [comment]
this should have been the default implementation, instead of using an AlertDialog, whoever made this library should have used `DialogFragment` instead.

**Comment by samtstern** [comment]
@k0shk0sh that's true, if you submit a PR I'd be happy to review.

**Comment by k0shk0sh** [comment]
@samtstern i would like to do that, however, as you might know, this would cause the EasyPermission class to be rewritten again. i'll try my best to make it compatible with older version. 
do expect a PR soon.

**Comment by samtstern** [comment]
@k0shk0sh I think it should be possible to make the new behavior mostly backwards compatible, we can always fall back to an `AlertDialog` if the calling `Activity` is not an instance of `FragmentActivity`.

**Comment by k0shk0sh** [comment]
I don't think that the instance of the object should matter, what really matter is that the activity is recreate-able or no. if i'm wrong please correct me.

**Comment by samtstern** [comment]
After looking around it seems like you can actually use a `DialogFragment` outside of `FragmentActivity` so you may be right.

**Comment by k0shk0sh** [comment]
Well, ok. i guess i might find a better solution to work around this, that does not require us to rewrite the whole library, i'll be trying it out and let you know the result.

**Comment by k0shk0sh** [comment]
PR has been submitted.

**Comment by samtstern** [comment]
Fixed by #52

**Comment by samtstern** [comment]
Version `0.2.1` release.
