### ISSUE TITLE
androidx support please

### ISSUE THREAD

**Issue by XinyueZ** [googlesamples/easypermissions#245]
For jetpack, this library can not be used if I use androidx namespace.

**Comment by samtstern** [comment]
@XinyueZ can you explain the error you're getting and how to reproduce it?

**Comment by XinyueZ** [comment]
@samtstern 
I have a project with androidx namespace which is from jetpack, 

i.e. 
```
androidx.appcompat.app.AppCompatActivity
androidx.appcompat.app.Fragment
....
```
however, the library is using `android.support.v4.app.Fragment` etc which is not awesome.
Actually, I can not use this library for jetpack project.

**Can the library starts snapshot for Jetpack, androidx namespace?**

**Comment by SUPERCILEX** [comment]
@XinyueZ We can't do that until everyone has migrated. In the meantime, [enable the Jetifier](https://developer.android.com/topic/libraries/support-library/androidx-overview):
![image](https://user-images.githubusercontent.com/9490724/44811318-37cf4580-ab89-11e8-940e-0d9ff546da8c.png)

**Comment by XinyueZ** [comment]
OK thanks, I close the ticket just for info of your side.

**Comment by samtstern** [comment]
Thanks @XinyueZ and @SUPERCILEX for resolving this!

**Comment by peterhav** [comment]
Just a minor question related to this, I decided to switch to AndroidX. In the UI of Android Studio I do see the following errors:

![image](https://user-images.githubusercontent.com/1724223/44946541-525e2480-adfe-11e8-8977-26291021ccf2.png)

The error says cannot resolve method (due to the fact that the method now receives a `androidx.fragment.app.Fragment`). Compilation works fine (using the Jetifier method). Is it normal that the UI shows these errors, or do I miss something?

**Comment by SUPERCILEX** [comment]
Are you using Android Studio 3.2?

**Comment by peterhav** [comment]
@SUPERCILEX, yes, I'm using 3.2 RC2, but nevermind: the error seems to have disappeared today. This could be related to a new version of the SDK Platform tools (28.0.1) which I installed today.

**Comment by XinyueZ** [comment]
If anyone has problem with easypermissions on Jetpack or under androidx namespace, 
I've converted easypermissions to support Jetpack which has androidx namespace 
http://tinyurl.com/y7qb2rr7

This is a workaround to mirror origin project, it won't be supported for any bug fixing etc, it is only for `androidx` namespace.

```groovy
implementation "com.github.xinyuez:easypermissions:1.3.0"
```
