### ISSUE TITLE
Unable to build while using Proguard

### ISSUE THREAD

**Issue by faizfolio** [googlesamples/easypermissions#247]
Device type: Samsung S8
OS version: 8.0.0
EasyPermissions version: 1.3.0

When I try to build, I am getting the following proguard warning. Due to which I am unable to build and run my app. 

```
Warning: pub.devrel.easypermissions.RationaleDialogClickListener: can't find referenced class android.arch.lifecycle.ViewModelStoreOwner
```

Gradle configurations for proguard in my build.gradle are
```         
minifyEnabled true
shrinkResources true
debuggable true
zipAlignEnabled true
```

Using following support libraries
```
supportlib_version = 27.0.1

implementation 'com.android.support:multidex:1.0.2'  
implementation "com.android.support:recyclerview-v7:$supportlib_version"        
implementation "com.android.support:cardview-v7:$supportlib_version"        
implementation "com.android.support:design:$supportlib_version"     
implementation "com.android.support:appcompat-v7:$supportlib_version"      
implementation "com.android.support:support-annotations:$supportlib_version" 
```
Note: **I am not using any of the architecture component in my project.** 

This works fine If I do not apply proguard. The question is then do I have to add any rules in my proguard file specfically for EasyPermissions?

Waiting for your response. Thanks

**Comment by SUPERCILEX** [comment]
I think you need to update your support lib version to 27.1.1

**Comment by samtstern** [comment]
Yeah @SUPERCILEX is probably right, the support libraries depend on some of the base architecture stuff which is why you're seeing it even without using it yourself.

**Comment by faizfolio** [comment]
If I add the following proguard rule in my proguard-rules.pro file the build problem resolves.

`
-dontwarn pub.devrel.**
`

Will this cause any problem?

**Comment by SUPERCILEX** [comment]
If you aren't getting linkage errors at runtime in your debug builds, you're probably fine. However, the easiest way to know for sure is to run a release build.

**Comment by samtstern** [comment]
Closing as I think @SUPERCILEX got to this, thanks!
