### ISSUE TITLE
Vivo Y75A permission failed

### ISSUE THREAD

**Issue by kk-sugar** [googlesamples/easypermissions#248]
## Basic Information

Device type: ___Vivo Y75A_____
OS version: ____Android 7.1____
EasyPermissions version: __1.3.0______

## Describe the problem
EasyPermissions.hasPermissions(this, Manifest.permission.CAMERA) returns true regardless of whether the authorization is turned off or on.
What happened?  What did you expect to happen?

## Code and logs

```
// TODO(you): show the code that produces the problem,
//            and any relevant logs.
```

**Comment by samtstern** [comment]
Closing since it's been a few weeks.  Let me know if you want to keep discussing and I'll reopen!
