### ISSUE TITLE
Error:(7) resource android:attr/dialogCornerRadius not found.    

### ISSUE THREAD

**Issue by chao9267** [googlesamples/easypermissions#260]
An error occurred： resource android:attr/dialogCornerRadius not found.    
when i Importing the version 2.0.0

**Comment by samtstern** [comment]
This looks similar to this question:
https://stackoverflow.com/questions/49280632/error9-5-error-resource-androidattr-dialogcornerradius-not-found

Have you tried that solution?  EasyPermissions depends on support lib 28.0.0, so you should raise your SDK versions to 28.
