### ISSUE TITLE
Application permission settings cannot be opened.

### ISSUE THREAD

**Issue by dielian-wizard-ly** [googlesamples/easypermissions#264]
## Basic Information

Device type: vivo x21
OS version: Android 28
EasyPermissions version: 2.0.0

Application permission settings cannot be opened.

when I denine permission, show open app settings tip,  choose sure,  Flash back to the application. cannot open Application permission settings interface? 

I try to add new `AppSettingsDialog.Builder(this).setOpenInNewTask(true).build().show()` ,  It can not be opened.

**Comment by samtstern** [comment]
@dielian-wizard-ly what happens when you call `.show()` like that?  Are there any errors in the `logcat`?  Does the app crash?

**Comment by samtstern** [comment]
It's been a while since there was any information posted here and there's not enough information to debug, so closing.
