### ISSUE TITLE
AndroidX migration?

### ISSUE THREAD

**Issue by nareshkatta99** [googlesamples/easypermissions#265]
The users who are Using AndroidX can not use this awesome library.
Please create another version for AndroidX migrated projects.

**Comment by samtstern** [comment]
@nareshkatta99 are you using Jetifier?  What problems are you having using this library with AndroidX?

**Comment by NoteJGPak** [comment]
@samtstern 

When using the library in Fragment, it says that android.support.v4.app.Fragment can not be found.

The reason is that if you use androidx you are using androidx.fragment.app.Fragment the corresponding fragment.

**Comment by sungerk** [comment]
+1

**Comment by samtstern** [comment]
This is being addressed in #272 and will be a part of release `3.0.0`

**Comment by samtstern** [comment]
Fixed and released in `3.0.0`
