### ISSUE TITLE
What are the dependencies occupy?

### ISSUE THREAD

**Issue by sebasrobert012** [googlesamples/easypermissions#274]
I would like to know the dependencies that they occupy, I am new programming :(

**Comment by samtstern** [comment]
You can see the library dependencies here:
https://github.com/googlesamples/easypermissions/blob/master/easypermissions/build.gradle#L36

Currently they are:
```
    api "androidx.appcompat:appcompat:1.0.2"
    api "androidx.core:core:1.0.1"
    api "androidx.fragment:fragment:1.0.0"
```
