### ISSUE TITLE
Prevent rationale and permission denied dialog from showing multiple times

### ISSUE THREAD

**Issue by yelinaung** [googlesamples/easypermissions#28]
My use case is that I have this "Shake to get the current location" which I show the request permission rationale dialog when the user shakes.
The tricky part is some users shake more than they should and the dialog appears more than one time.

I am sure this might not be case for most people and the simplest fix would be just

```java
if(!dialog.isShowing()) {
    dialog.show();
}
```
in both `requestPermissions` and `checkDeniedPermissionsNeverAskAgain`. 
If this is trivial, I would just include the source codes in the app and make the change myself. 
Otherwise, I could send a PR. 

Thanks for the awesome lib!

**Comment by yelinaung** [comment]
Right after opening the issue, I did a work around without changing anything. So, if you guys feel this change is not necessary, please feel free to close this issue. :)

**Comment by samtstern** [comment]
@yelinaung thanks for the report.  It's probably better to just change something on the app side like you did, but of course if you want to submit a PR that fixes this internally I would be more than happy to review it.

I'll close the issue for now, since it's an optional fix.
