### ISSUE TITLE
 permissionsgranted and permissionsdenied will be called continuously.

### ISSUE THREAD

**Issue by centerzx** [googlesamples/easypermissions#292]
## Basic Information

Device type: ___xiao mi 4S_____
OS version: ___7.0_____
EasyPermissions version: ___2.0.1_____

##DES：
Request permission: manifest.permission.camera, manifest.permission.record'audio, manifest.permission.write'external'storage, manifest.permission.read'external'storage

Among them, 2 are allowed, 1 is denied, and the operation method is added to the onpermissionsgranted method, and then click the button to request permission. At this time, permissionsgranted and permissionsdenied will be called continuously.

What happened?  What did you expect to happen?

## Code and logs

```java
public void grantedStartLive() {
        String[] perms = new String[]{Manifest.permission.CAMERA, Manifest.permission.RECORD_AUDIO, Manifest.permission.WRITE_EXTERNAL_STORAGE, Manifest.permission.READ_EXTERNAL_STORAGE};
        if (EasyPermissions.hasPermissions(getActivity(), perms)) {
            startLive();
        } else {
EasyPermissions.requestPermissions(getActivity(),App.getApplication().getString(R.string.permission_live_req_tips), PermissionUtil.LIVE_PERMISSION_CODE, perms);
        }
    }

@Override
public void onPermissionsGranted(int requestCode, @NonNull List<String> perms) {
        if (requestCode == PermissionUtil.LIVE_PERMISSION_CODE) {
            grantedStartLive();
        }
    }

@Override
public void onPermissionsDenied(int requestCode, @NonNull List<String> perms) {
        if (EasyPermissions.somePermissionPermanentlyDenied(this, perms)) {
            if (requestCode == PermissionUtil.LIVE_PERMISSION_CODE) {
                showLivePermissionDialog();
            } 
        }
    }
```

...........THX

**Comment by bitvale** [comment]
Try to add `perms` size check in `onPermissionsGranted`:

    if (requestCode == PermissionUtil.LIVE_PERMISSION_CODE) {
            if (perms.size() == 4) {
                   grantedStartLive(); 
            }
    }

**Comment by samtstern** [comment]
Sorry I never responded here!  I totally missed this.  @bitvale has the correct solution though, `onPermissionsGranted` will be called even if only some permissions are granted.
