### ISSUE TITLE
Empty Rationale Dialog with cancel and ok button.

### ISSUE THREAD

**Issue by hemantparmar23** [googlesamples/easypermissions#294]
## Basic Information

Device type: _Xiaomi Redmi Note 7 Pro_
OS version: __9.0______
EasyPermissions version: _3.0.0_(androidX)

## Describe the problem
While trying to integrate easypermissions into my app. The permissions work fine the first time but when rationale dialog is supposed to be shown (the second time I request permission after the first time it was denied) I get a empty rationale dialog even though I am supplying proper text to it. 
What happened?  What did you expect to happen?
The rationale dialog was missing the text supplied. The text should have been there.
## Code and logs

```
@AfterPermissionGranted(RC_CAMERA_PERM)
    public void cameraTask() {
        if (hasCameraPermission()) {
            // Have permission, do the thing!
            Toast.makeText(this, "TODO: Camera things", Toast.LENGTH_LONG).show();
        } else {
            // Ask for one permission
            EasyPermissions.requestPermissions(
                    this,
                    getString(R.string.permission_storage_rationale),
                    RC_CAMERA_PERM,
                    Manifest.permission.CAMERA);
        }
    }
```
![test](https://user-images.githubusercontent.com/1955738/70727642-fe8efa80-1d25-11ea-95e4-477d9dd60236.png)

**Comment by samtstern** [comment]
This looks like it might be a theme issue?  The buttons in the picture have
a grey background and white text.  If the text in the dialog is white it
would be invisible.

Can you try changing your app theme temporarily to a darker text color and
see if you can see the text?

**Comment by hemantparmar23** [comment]
Thanks
It was indeed a styling issue on my part.
