### ISSUE TITLE
Questions about using easypermissions version 1.3.0

### ISSUE THREAD

**Issue by moyinqingshang** [googlesamples/easypermissions#295]
## Basic Information

Device type: ________
OS version: ________
EasyPermissions version: ____1.3.0____

## Describe the problem
Due to other reasons, the project can only use targetSdkVersion 27 at present and cannot upgrade to targetSdkVersion 28. May I ask if there are any bugs or impacts if version 1.3.0 of easypermissions is used?
What happened?  What did you expect to happen?

## Code and logs

```
// TODO(you): show the code that produces the problem,
//            and any relevant logs.
```

**Comment by samtstern** [comment]
You can see the changes in each version here:
https://github.com/googlesamples/easypermissions/releases

You can still use 1.3.0 if you want to, you just won't get the features and bug fixes from later releases.
