### ISSUE TITLE
how can i remove rationale dialog?

### ISSUE THREAD

**Issue by HarveyLeeChn** [googlesamples/easypermissions#296]
## Basic Information

Device type: ________
OS version: ________
EasyPermissions version: ________

## Describe the problem

What happened?  What did you expect to happen?

## Code and logs

```
// TODO(you): show the code that produces the problem,
//            and any relevant logs.
```

**Comment by samtstern** [comment]
@HarveyLeeChn you cannot.  EasyPermissions is an opinionated library that implements the recommended flows.  If you want custom flows you will have to use the base permissions API yourself.

**Comment by BodhiSun** [comment]
Hello ,when i looked at the EP(3.0.0) source code,I found requestPermissions(...) method which contains a toggle method 'shouldShowRationale()', i found it relies on Activity's(or Fragment) method,so when i override Activity's(or Fragment) 'shouldShowRequestPermissionRationale(...)' method and return false,The rationale dialog really skips;

**Comment by xgeeek** [comment]
> Hello ,when i looked at the EP(3.0.0) source code,I found requestPermissions(...) method which contains a toggle method 'shouldShowRationale()', i found it relies on Activity's(or Fragment) method,so when i override Activity's(or Fragment) 'shouldShowRequestPermissionRationale(...)' method and return false,The rationale dialog really skips;

Yes, you are right!

**Comment by xgeeek** [comment]
> Hello ,when i looked at the EP(3.0.0) source code,I found requestPermissions(...) method which contains a toggle method 'shouldShowRationale()', i found it relies on Activity's(or Fragment) method,so when i override Activity's(or Fragment) 'shouldShowRequestPermissionRationale(...)' method and return false,The rationale dialog really skips;

exactly
