### ISSUE TITLE
PermissionCheck: permission check result is: 601

### ISSUE THREAD

**Issue by lovehahazy** [googlesamples/easypermissions#297]
## Basic Information

Device type: ______华为V10_全网通
OS version: ________
EasyPermissions version: ________3.0.0
gradle:3.5.3   Androidx

## Describe the problem
程序有崩溃，在日志中发现这样的代码：
02-14 16:49:27.386 15560 15560 E PermissionCheck: permission check result is: 601

**Comment by samtstern** [comment]
@lovehahazy sorry this is not enough information to debug.  I would need code to reproduce the problem and more logs that show exactly where this code is coming from!  If you need help but can't provide those things, please try StackOverflow.

**Comment by lovehahazy** [comment]
Sorry to bother you. I think I need to further identify the root cause of the problem. Maybe the problem is somewhere else. If I can further prove that the problem is from here, I will leave a message. I'm really sorry.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Sam Stern"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月15日(星期六) 凌晨1:21
收件人:&nbsp;"googlesamples/easypermissions"<easypermissions@noreply.github.com&gt;;
抄送:&nbsp;"畅想"<1171660883@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [googlesamples/easypermissions] PermissionCheck: permission check result is: 601 (#297)




@lovehahazy sorry this is not enough information to debug.  I would need code to reproduce the problem and more logs that show exactly where this code is coming from!  If you need help but can't provide those things, please try StackOverflow.
