### ISSUE TITLE
app  crash   :PermissionCheck: permission check result is: 601

### ISSUE THREAD

**Issue by lovehahazy** [googlesamples/easypermissions#298]
## Basic Information

Device type: _______华为 note 4e   ；华为v10 全网通
OS version: ________
EasyPermissions version: ________3.0.0

## Describe the problem

When we use the cloud real machine to test, we find that the application will crash. The error log contains the following：
“02-14 16:49:27.386 15560 15560 E PermissionCheck: permission check result is: 601”

**Comment by lovehahazy** [comment]
Sorry to bother you. I think I need to further identify the root cause of the problem. Maybe the problem is somewhere else. If I can further prove that the problem is from here, I will leave a message. I'm really sorry.

**Comment by lovehahazy** [comment]
Finally, the problem is solved. It has nothing to do with this library. I made a mistake

**Comment by samtstern** [comment]
@lovehahazy thank you for updating this!
