### ISSUE TITLE
Private methods with @AfterPermissionGranted annotation is not executed

### ISSUE THREAD

**Issue by saggafarsyad** [googlesamples/easypermissions#3]
I was looking at Request Permission example in Readme.md. I don't know if this is a bug or not, but private methods with @AfterPermissionGranted annotation will not be executed. I debug and found out in EasyPermissions.java line 176, getMethods() returns public methods according to JavaDoc

I change my method to public and it works.

**Comment by samtstern** [comment]
This is definitely working as intended right now, but maybe it's possible to make it work for private methods. 

If you know how to use reflection to find and invoke a private method without knowing its name, please submit a pull request and I'd be happy to merge it.

**Comment by afollestad** [comment]
Using `getDeclaredMethod(String)` or `getDeclaredMethods()` will retrieve non-public methods in addition to public methods.

**Comment by samtstern** [comment]
Fixed in #4
