### ISSUE TITLE
how implement in kotlin sir? thank you

### ISSUE THREAD

**Issue by IqbalAlhadadgreenhcm321** [googlesamples/easypermissions#315]
EasyPermissions.requestPermissions(
        new PermissionRequest.Builder(this, RC_CAMERA_AND_LOCATION, perms)
                .setRationale(R.string.camera_and_location_rationale)
                .setPositiveButtonText(R.string.rationale_ask_ok)
                .setNegativeButtonText(R.string.rationale_ask_cancel)
                .setTheme(R.style.my_fancy_style)
                .build());

i copy your code in my function but many error

**Comment by samtstern** [comment]
@IqbalAlhadadgreenhcm321 this issue tracker is for bugs in the library, please use StackOverflow for general questions.
