### ISSUE TITLE
Library artifacts are published to jcenter only, which will close in 3 months

### ISSUE THREAD

**Issue by entibaldi** [googlesamples/easypermissions#319]
## Basic Information

Hello! Your library is published only to jcenter. Please consider publishing it also to mavenCentral, as jcenter is [shutting down in May](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

[Here](https://central.sonatype.org/pages/producers.html) is some info on how to publish artifacts to mavenCentral.

**Comment by samtstern** [comment]
@entibaldi thanks for the issue!  We're looking into it

**Comment by adrynov** [comment]
Any updates on this issue?

Time is running out and this does not work:

 ```
repositories {
        google()
//        mavenCentral()
        jcenter()
        // https://jeroenmols.com/blog/2021/02/04/migratingjcenter/
            jcenter() {
                content {
                    includeModule("pub.devrel", "easypermissions")
                }
            }
    }
```

The result is:

> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find pub.devrel:easypermissions:3.0.0.
     Required by:
         project :app

**Comment by samtstern** [comment]
I just published version `3.0.0` to Maven Central, it should be available now or maybe in a few minutes when the caches clear.

**Comment by samtstern** [comment]
Confirmed:
https://repo1.maven.org/maven2/pub/devrel/easypermissions/3.0.0/

**Comment by adrynov** [comment]
This was swift, thank you!

**Comment by gsapo** [comment]
Hello,
Can you move the "pub.devrel:easypermissions:2.0.1" also to mavenCentral()? Because I'm using the Android Support Library and JCenter is down. Thank you!
