### ISSUE TITLE
rationale string not display in the very first time permission request

### ISSUE THREAD

**Issue by farhad-kargaran** [googlesamples/easypermissions#32]
EasyPermissions.requestPermissions(this, "I need this",  100 , perms);

The sentence "I need this" not displayed the very first time in requesting permission, but for further more request it will display.
If I turn permission on and off it again from setting. the sentence not display again for first request!

I am using easypermissions:0.1.8 on LG G4 H815P  android 6.0

**Comment by samtstern** [comment]
@farhad-kargaran that's how the Android permissions system works.  Rationale is only shown after the user has denied the permission once.

**Comment by farhad-kargaran** [comment]
ok thank you
