### ISSUE TITLE
how to define RC_CAMERA_AND_LOCATION, and what is the value of 'camera_and_location_rationale' in example 

### ISSUE THREAD

**Issue by astraydog** [googlesamples/easypermissions#329]
## Basic Information

Device type: __Emulator______
OS version: ____android 9.0____
EasyPermissions version: ____2.0.1____

## Describe the problem

What I want is record the screen actions and save it to /storage/emulated/0/Download/.
how to define RC_CAMERA_AND_LOCATION? It says Cannot resolve symbol 'RC_CAMERA_AND_LOCATION'.
And what is the value of 'R.string.camera_and_location_rationale'

I have define permissions in AndroidManifest.xml.
```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.RECORD_AUDIO" 
```
## Code and logs

```
// TODO(you): show the code that produces the problem,
@AfterPermissionGranted(RC_CAMERA_AND_LOCATION)
private void methodRequiresTwoPermission() {
    String[] perms = {Manifest.permission.CAMERA, Manifest.permission.ACCESS_FINE_LOCATION};
    if (EasyPermissions.hasPermissions(this, perms)) {
        // Already have permission, do the thing
        // ...
    } else {
        // Do not have permissions, request them now
        EasyPermissions.requestPermissions(this, getString(R.string.camera_and_location_rationale),
                RC_CAMERA_AND_LOCATION, perms);
    }
}
```

**Comment by samtstern** [comment]
@astraydog `RC_CAMERA_AND_LOCATION` can be any integer. `RC_` means "Request Code" and it's how we'll uniquely identify the permission request.

So you can just do:

```java
// Value really doesn't matter as long as it's unique!
public static final int RC_CAMERA_AND_LOCATION = 123;
```

`R.string_camera_and_location_rationale` is just a custom string you want to show to the user explaining why you want the permission.  It could be something like this:
https://github.com/googlesamples/easypermissions/blob/2b2b5c40d11caf601c89da0af995f57772a2e52b/app/src/main/res/values/strings.xml#L6
