### ISSUE TITLE
Having issues getting the newest version.

### ISSUE THREAD

**Issue by tru2malice** [googlesamples/easypermissions#34]
Failed to resolve: pub.devrel:easypermissions:0.1.9  
But 0.1.8 still works No Problem. 

"---Edit---" It works if I use:

compile 'pub.devrel:easypermissions:0.1.9@aar'

**Comment by kongnanlive** [comment]
me too

**Comment by samtstern** [comment]
@tru2malice thanks for the report, it looks like my POM got lost in the last upload.  I have fixed it now and you should be able to use `0.1.9` without the `@aar` suffix.
