### ISSUE TITLE
RuntimeException has wrong message

### ISSUE THREAD

**Issue by tsadoklf** [googlesamples/easypermissions#36]
The RuntimeException thrown in runAnnotatedMethods method in the following if block has wrong message - 

`  if (method.getParameterTypes().length > 0) {
                        throw new RuntimeException(
                                "Cannot execute non-void method " + method.getName());
                    }`

The message should say something like "Cannot execute method [method name] because it is non-void method and/or has input parameters"

**Comment by Hackmodford** [comment]
This helped. I also suggest @tsadoklf made a pull request

**Comment by samtstern** [comment]
Version `0.2.1` released with this fix.

**Comment by Allyns** [comment]
I have also encountered this problem

**Comment by samtstern** [comment]
Make sure the method you annotate with `AfterPermissionGranted` is a `void` method with no parameters.

**Comment by Allyns** [comment]
This question has been resolved, thank you

**Comment by alphater** [comment]
@samtstern  Solution to force, actually can not take parameters

**Comment by faith-hb** [comment]
> Make sure the method you annotate with `AfterPermissionGranted` is a `void` method with no parameters.

Still won't do
