### ISSUE TITLE
Could not create plugin of type 'AndroidMavenPlugin'

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/easypermissions#40]
Hello,
upon building your app in Android Studio 2.2 Beta 2 with gradle plugin **com.android.tools.build:gradle:2.2.0-beta2**, I get the following error:
> Error:FAILURE: Build failed with an exception.
* Where:
Script '/Users/igorganapolsky/workspace/git/google/easypermissions/easypermissions/maven.gradle' line: 1
* What went wrong:
A problem occurred evaluating script.
> Failed to apply plugin [id 'com.github.dcendents.android-maven']
   > Could not create plugin of type 'AndroidMavenPlugin'.

If I debug the build from commandline, I see the following info:
> Caused by: org.gradle.internal.service.UnknownServiceException: No service of type Factory<LoggingManagerInternal> available in ProjectScopeServices.

Any ideas?

Thanks,
Igor

**Comment by samtstern** [comment]
@IgorGanapolsky does this happen when you downgrade back to `classpath 'com.android.tools.build:gradle:2.1.0'` ?

**Comment by IgorGanapolsky** [comment]
@samtstern If I use **com.android.tools.build:gradle:2.1.0**, then I cannot use Gradle **2.14.1**.  So it makes us stuck on old gradle versions.  But yes, that seems to fix the problem.

**Comment by samtstern** [comment]
@IgorGanapolsky ok I will dig into this when I get a chance, unfortunately the current workaround is to use the older version of gradle (through the gradle wrapper)

**Comment by faith-hb** [comment]
Add in the gradle file:
implementation 'com.squareup.retrofit2:adapter-rxjava:2.4.0'
