### ISSUE TITLE
I just don't know where to feedback the issue

### ISSUE THREAD

**Issue by specloli** [googlesamples/easypermissions#42]
why the nexus 6 and nexus6p didn't recevice nougat update anymore . THe release date is 8 -22..Two weeks later ,the old device have not recevice it ...I even want to change my phone to iphone 7 .  why ?
THere can't be any tech issuse...The only reason should be you want sell the new nexus ...

**Comment by specloli** [comment]
And it is so bad..If this month it didn't come yet.I will buy iPhone And make my Nexus 6 a nethunter device .

**Comment by samtstern** [comment]
@specloli this is not the right place to give feedback on general Android issues. Please only file issues here that have to do with the EasyPermissions library.

**Comment by specloli** [comment]
I think you should tell me where to go . we are all android developer.  i start build my aosp rom .and i want to say .  nexus is good but what google do  is really bad.
