### ISSUE TITLE
request permission method void ?? change it to boolean

### ISSUE THREAD

**Issue by Khoosham** [googlesamples/easypermissions#45]
```
 if(EasyPermissions.requestPermissions(this, "This App requires certain dangerous permission that you need to activate. Allow...?", PERM, perms)){
                    //return true here means user has accept to allow viewing the permission prompt
                } else {
                    //return false here exit the app.
                }

```

is it possible to change void and make it boolean.

i want to check the statement above if ever the user clicks cancel he is allowed in the app which i don't want only if return true then allow
in the return false i want to exit the app if he deny the message permission

[Image](http://prntscr.com/cl3zuh)
actually at the moment its not the case because its VOID can you make the change..Thanks in adv...

**Comment by samtstern** [comment]
@Khoosham we don't know right away if the user accepted or denied the permission, we can't synchronously return a `boolean` here.  You can use the `onPermissionsDenied` callback to do that.

**Comment by Khoosham** [comment]
Thanks i got it working :+1:
