### ISSUE TITLE
Add please the ability to make dialogs noncloseable please!

### ISSUE THREAD

**Issue by amperas17** [googlesamples/easypermissions#49]
Add .setCancelable(false) to AppSettingsDialog.Builder and to EasyPermissions.requestPermissions.
I want user could only press yes or no but couldn`t close dialog by click out of dialog area.

**Comment by refaelsh** [comment]
+1

**Comment by samtstern** [comment]
I think this is a good suggestion, I think non-cancelable is a good default.  I'll likely do this for the `0.2.0` release.

**Comment by k0shk0sh** [comment]
in the latest commit to my PR, i made the Rationale & the AppSettings Dialog to not be cancellable.

**Comment by samtstern** [comment]
Fixed by #52, release coming soon.

**Comment by samtstern** [comment]
Published in version `0.2.1`

**Comment by amperas17** [comment]
Thank you, but you make only EasyPermissions.requestPermissions dialog nonclosable and AppSettingsDialog still could be closed!

**Comment by samtstern** [comment]
@amperas17 yes that's true.  I will open an issue to track the second case.

**Comment by refaelsh** [comment]
Was an issue opened regarding "AppSettingsDialog still could be closed!"?

**Comment by samtstern** [comment]
@refaelsh yes that's #54
