### ISSUE TITLE
Make AppSettingsDialog non-closeable and survive rotation

### ISSUE THREAD

**Issue by samtstern** [googlesamples/easypermissions#54]
Similar to what was done in #53 for the rationale dialog.

**Comment by refaelsh** [comment]
+1

**Comment by mhmada** [comment]
#54

**Comment by MahmoudAlyuDeen** [comment]
+1
Or at least have an option in the builder to set a listener for dialog dismissal, that way we can handle users simply clicking outside.

**Comment by samtstern** [comment]
This is fixed by #75.  Will be released in the next version.
