### ISSUE TITLE
Exceptions?

### ISSUE THREAD

**Issue by davin12x** [googlesamples/easypermissions#55]
it's a weird issue
when i use plugin     compile 'pub.devrel:easypermissions:0.1.9'

Everything works perfects 
As soon as I moved to latest build    compile 'pub.devrel:easypermissions:0.2.1'

I got binary XML exception on floating button, coordinate layouts?

**Comment by samtstern** [comment]
Can you copy the exact exception you're getting here?  And what about
version 0.2.0?

**Comment by samtstern** [comment]
@davin12x since it's been 2 weeks and I have not gotten any other reports I am going to close this issue.  However since it does sound like a serious crash, if you can provide more information I would be happy to re-open and discuss.
