### ISSUE TITLE
Error:(404, 23) 错误: 找不到符号

### ISSUE THREAD

**Issue by s3hengwu** [googlesamples/easypermissions#58]
Error:(404, 23) 错误: 找不到符号
符号:   方法 isAnnotationPresent(Class<AfterPermissionGranted>)
位置: 类型为Method的变量 method

**Comment by samtstern** [comment]
@s3hengwu I'm sorry I don't speak Chinese and I tried to use Google Translate but I still don't understand the issue here.  Maybe you could try StackOverflow or another forum to get help?
