### ISSUE TITLE
Support for Overlay or DrawOverOtherApps Permission

### ISSUE THREAD

**Issue by rupinderjeet** [googlesamples/easypermissions#60]
Generally, this permission is allowed for most of the devices and APIs. It is a part of SYSTEM_ALERT_WINDOW permission. Following devices and APIs specially need to request it to draw over other apps. For e.g. drawing Chat Heads like Facebook Messenger.

> Android KitKat 4.4 - 4.4.2
> Android Marshmallow 6.0.0+ (not sure about 6.0.0+)
> Xiaomi's Redmi
> Meizu phones

I check for this permission like this:
```java
if (!Settings.canDrawOverlays()) {
      // request the permission
} else { 
      // continue, permission is allowed
      doSomething();
}
```

I, also, check that back in `onResume()`

Can you support this?

**Comment by samtstern** [comment]
@rupinderjeet it seems that getting that permission requires sending an Intent with `ACTION_MANAGE_OVERLAY_PERMISSION`, which has a totally different lifecycle when compared to other permissions.

While I am not opposed to adding this support in theory, I am concerned that it will be hard to fit into the mental model of this library and it may be better handled separately.

**Comment by rupinderjeet** [comment]
You're right. It wouldn't fit in the regular permission request and retrieval model.
