### ISSUE TITLE
Request dialog not being thrown

### ISSUE THREAD

**Issue by tryadelion** [googlesamples/easypermissions#68]
When requesting permissions using EasyPermissions request method, the permission goes automatically to denied without showing any kind of dialog.
![captura de pantalla 2016-12-21 a las 16 33 33](https://cloud.githubusercontent.com/assets/3778474/21395189/db624702-c79b-11e6-9aac-b156b9a9b4c9.png)

**Comment by samtstern** [comment]
@tryadelion do you have those permissions declared in your manifest?  Also is the device you're using running Marshmallow or later?

**Comment by tryadelion** [comment]
Yup, and Yup. it's 6.0.1 Android running on a BQ M5, the permissions are declared, and as soon as i debug the requestPermissions() bit of code, it jumps to onPermissionDenied. tried deleting the app, just incase someone messed with my permissions, and reinstalled it, and got the same result.

**Comment by samtstern** [comment]
@tryadelion huh ok, that's very strange.  Is this device specific?  Could you try your code on an Android emulator to make sure it works there?

**Comment by tryadelion** [comment]
For some reason, wiping up AS (clear cached things and running a build clean) after some vacation days made it work. something somehow got stuck in there. Anyway, it works now, thank you very much for your help.

**Comment by samtstern** [comment]
@tryadelion :man_shrugging: glad it worked!
