### ISSUE TITLE
Library does not work with android.app.Fragment, only with android.support.v4.app.Fragment

### ISSUE THREAD

**Issue by pepe-pa** [googlesamples/easypermissions#7]
Library does not work with android.app.Fragment, only with android.support.v4.app.Fragment

**Comment by samtstern** [comment]
@pepe-pa using the support library is considered best practice, could you provide some more information as to why that does not work for your application>

**Comment by pepe-pa** [comment]
Yes, of course, but with minApiLevel 15 it is not necessary to use support fragment and system permission system does not work only with support Fragments

**Comment by samtstern** [comment]
The minSdk of this library is 9.  I would suggest using android.support.v4.Fragment in your app rather than changing this library to support system Fragments (which I do not intend to do currently).

**Comment by k0shk0sh** [comment]
how about Preference Fragment?

**Comment by samtstern** [comment]
@k0shk0sh not currently supported but that's a valid feature request.  I'll open a new issue for that.

**Comment by samtstern** [comment]
@pepe-pa @k0shk0sh as of #21 this library now works with android.app.Fragment
