### ISSUE TITLE
Infinite loop if i have a method that need runtime permission in onResume().

### ISSUE THREAD

**Issue by mrldroid** [googlesamples/easypermissions#70]
when requesting permission in onResume(), i deny the permission with the "Never Ask Again" option,then show AppSettingsDialog. However it seems the onResume() is always running,and the AppSettingsDialog splash all the time.

**Comment by samtstern** [comment]
@mrldroid can you provide some code that demonstrates the problem?

**Comment by samtstern** [comment]
@mrldroid it's been over two weeks since the last update so I am going to close this issue.  Please re-open if you want to discuss further.
