### ISSUE TITLE
InflateException of inflating class android.support.design.widget.FloatingActionButton 

### ISSUE THREAD

**Issue by Bertkiing** [googlesamples/easypermissions#71]
![dfs](https://cloud.githubusercontent.com/assets/19733128/21705629/138408f2-d3fc-11e6-8816-81ddf7cf173a.png)

I try many times but the error also occur,and I cofirm the cause is use your library...

**Comment by samtstern** [comment]
@Bertkiing can you show your `build.gradle` file?

**Comment by Bertkiing** [comment]
Ok,I guess you just want this:
![project](https://cloud.githubusercontent.com/assets/19733128/21762879/00b0b120-d696-11e6-9b42-82afdb9c19d3.png)
![app](https://cloud.githubusercontent.com/assets/19733128/21762886/0c10f89a-d696-11e6-8cc0-cff721af3706.png)

Thanks for your reply!

**Comment by samtstern** [comment]
@Bertkiing I'd like to see the `dependencies` block from the file in the second screenshot.

**Comment by Bertkiing** [comment]
I'm so sorry for cannot reply to you in time. This is :
![error](https://cloud.githubusercontent.com/assets/19733128/21841791/c64ede28-d81e-11e6-991a-33080d07e903.png)
Hope to help you.

**Comment by samtstern** [comment]
The latest version of EasyPermissions is targeting support library versions `25.0.0`.  Could you try updating your support libraries to some `25.*` version and seeing if that helps?  I suspect it will.

**Comment by Bertkiing** [comment]
## Despite my best effort though, I could not achieve the required---update **# all** libraries to 25.., you can see that 
![error](https://cloud.githubusercontent.com/assets/19733128/21886782/30ab67f8-d8f8-11e6-8623-166b8aca43f5.png)

Recently ,I having too much work  so than I cannot help  you absolutely ,  when I am free I will check the problem again.

**Comment by samtstern** [comment]
@Bertkiing `25.4.0` does not exist.  Try `25.1.0`

**Comment by Bertkiing** [comment]
Cool beans! Thanks a billion.

**Comment by SUPERCILEX** [comment]
@samtstern, I believe this issue has been resolved.
