### ISSUE TITLE
Rationale dialog is not showing buttons

### ISSUE THREAD

**Issue by sandeeptengale** [googlesamples/easypermissions#77]
Rationale button which showing the message on the first rejection of the permission is not showing any of the buttons like 'ok' or 'cancel'. 

User will not get to know what to do in that case.

I checked it on Samsung s6 and Moto G4 plus

**Comment by samtstern** [comment]
@sandeeptengale do you have a screenshot?  Also what version of easypermissions are you using?

**Comment by sandeeptengale** [comment]
Am using 0.2.1 version, unable to share screenshot here as github having some problem in image loading. 

I can describe it, it shows the rationale message in a dialog box with no cancel or ok button. Just a dialog box with message I set.

**Comment by samtstern** [comment]
@sandeeptengale can you try running the sample app that is included with this repository and see if it displays the same problem?  That will help narrow down the cause

**Comment by sandeeptengale** [comment]
It's because of accent color which is very light to see. I changed it to black, it started showing cancel and ok.
Thanks
