### ISSUE TITLE
Why multiple request asked at the same time?

### ISSUE THREAD

**Issue by vipulasri** [googlesamples/easypermissions#80]
At starting of the app, I have READ_SMS permission and WRITE_EXTERNAL_STORAGE permission after signup.
Now the issue is as soon as I allow READ_SMS permission, it asks me for WRITE_EXTERNAL_STORAGE permission after that only(signup not done). How to stop this behavior and ask user permission only when required.

**Comment by samtstern** [comment]
@vipulasri I don't quite understand your issue, can you post some code that reproduces the problem?

**Comment by vipulasri** [comment]
@samtstern I mean I am asking two different permissions on two different activities or fragments but as soon as first activity asks for a permission only related to that activity (Ex. Send OTP screen asks for READ_SMS) then another permission (i.e WRITE_EXTERNAL_STORAGE) on another activity and that screen is not yet called or displayed. Still, after allowing first READ_SMS permission, it asks for second permission WRITE_EXTERNAL_STORAGE. 

```
@Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        EasyPermissions.onRequestPermissionsResult(requestCode, permissions, grantResults, this);
    }
```
Do I have to change `onRequestPermissionResult()` method calling `super`

**Comment by samtstern** [comment]
@vipulasri so you have two fragments in the same Activity requesting different permissions?  Where do you actually call `reuestPermissions`?

**Comment by vipulasri** [comment]
@samtstern No, I have one request permission in a fragment associated with another activity and second request permission in different activity.

**Comment by samtstern** [comment]
@vipulasri please show me how you are requesting the SMS permission.

**Comment by vipulasri** [comment]
```
@AfterPermissionGranted(RC_READ_SMS_PERM)
    public void initiateOtp() {
        //do nothing, not needed as sms has already been sent
        if (EasyPermissions.hasPermissions(getActivity(), Manifest.permission.READ_SMS)) {
            initiateVerification();
        } else {
            EasyPermissions.requestPermissions(this, getString(R.string.readsms_permission), RC_READ_SMS_PERM, Manifest.permission.READ_SMS);
        }
    }
```

**Comment by samtstern** [comment]
And where do you request the external storage permission?  I need some context with these code snippets, the behavior you're describing is guaranteed to be some strange issue in how your code is set up so only showing me basic code will not get to the root of the problem.

**Comment by vipulasri** [comment]
I request the external storage permission(if not permitted), whenever the user has to select a picture from the device and upload it. And request external storage permission is implemented in BaseActivity so that I can reuse the feature when needed.

**Comment by samtstern** [comment]
Are you re-using the same request code for each (`RC_READ_SMS_PERM`)?  Try using different request codes in the `requestPermissions` and `@AfterPermissionGranted` annotations.

**Comment by vipulasri** [comment]
I am already using different request codes for both permission requests.

**Comment by samtstern** [comment]
@vipulasri I am going to need to see more code to debug, there has not been enough information provided in this thread to lead to the source of the problem.  If you'd prefer this can be done on StackOverflow.

**Comment by vipulasri** [comment]
@samtstern I figured out the problem. Problem was I was having external storage permission in my base activity and the activity which was requiring permission for read sms was extending BaseActivity which was creating issue as `onRequestPermissionsResult` was calling its super method thus calling base activity `onRequestPermissionsResult`.
