### ISSUE TITLE
if user grante all permissions very quickly ,then the app will crash

### ISSUE THREAD

**Issue by usedlie** [googlesamples/easypermissions#81]
if one use this repository normal,then everything is fine;
but i try to test it :)
step 1:
uninstall the app ,and then install app,then  grant all permissions very quickly ,then the app will crash;
i don't see the crash log :( ..
but i reopen the app,and crash again ,and see the log:

`02-09 14:14:54.695 3013-3013/com.hgrica.obdclient E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.hgrica.obdclient, PID: 3013
                                                                    java.lang.ClassCastException: com.hgrica.obdclient.view.WelcomeActivity cannot be cast to android.support.v4.app.FragmentActivity
                                                                        at pub.devrel.easypermissions.RationaleDialogClickListener.onClick(RationaleDialogClickListener.java:57)
                                                                        at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:161)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:150)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)`

_____
i notice this :`com.hgrica.obdclient.view.WelcomeActivity cannot be cast to android.support.v4.app.FragmentActivity`
that means i should use a activity that extends FragmentActivity?
but u never mention it..
_____

step2:
uninstall the app,and reinstall the app.oh.still the app crash again.
i notice a important thing: ` EasyPermissions.hasPermissions(this, PERMISSIONS_ALL) in the method which has @AfterPermissionGranted(REQUEST_ALL) ` dosen't work well;i have already granted all permissions,but  EasyPermissions.hasPermissions(this, PERMISSIONS_ALL) still return false until i restart the app or just grant the permission(although i have already granted it)again.

:(
___
here is the activity code :)
`public class WelcomeActivity extends BaseFragmentActivity implements EasyPermissions.PermissionCallbacks{
    private static final String TAG = WelcomeActivity.class.getSimpleName();

    //all permission i want
    public static String[] PERMISSIONS_ALL = {Manifest.permission.READ_EXTERNAL_STORAGE,
            Manifest.permission.WRITE_EXTERNAL_STORAGE,Manifest.permission.ACCESS_FINE_LOCATION,
            Manifest.permission.ACCESS_COARSE_LOCATION, Manifest.permission.READ_PHONE_STATE
    };
    //all
    public static final int REQUEST_ALL = 4;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_welcome);
        requestPermissions();
    }

    private void requestPermissions() {
        requestAllPermissions();
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        EasyPermissions.onRequestPermissionsResult(requestCode, permissions, grantResults, this);
    }

    @Override
    public void onPermissionsGranted(int requestCode, List<String> perms) {
        LogUtil.d(TAG,"onPermissionsGranted(),requestCode:"+requestCode);
        for (String perm:perms){
            LogUtil.d(TAG,"onPermissionsGranted(),perm:"+perm);
        }
    }

    @Override
    public void onPermissionsDenied(int requestCode, List<String> perms) {
        LogUtil.d(TAG,"onPermissionsDenied(),requestCode:"+requestCode);
        for (String perm:perms){
            LogUtil.d(TAG,"onPermissionsDenied(),perm:"+perm);
        }
    }

    @AfterPermissionGranted(REQUEST_ALL)
    private void requestCodeQRCodePermissions() {
        if (!EasyPermissions.hasPermissions(this, PERMISSIONS_ALL)) {
            LogUtil.d(TAG,"what~~~~~~~~~~~no");
            EasyPermissions.requestPermissions(this, "come on", REQUEST_ALL, PERMISSIONS_ALL);
        }else {
            // Already have permission, do the thing
            LogUtil.d(TAG,"what~~~~~~~~~~~yes");
        }
    }
}`

___
so i try to do sth for these problem:

step1: i try to make activity extends FragmentActivity..
it work! well..er..fine.

setp2: still finding way.....
so i need your help!!thx

**Comment by SUPERCILEX** [comment]
@usedlie I'm pretty sure this was fixed in https://github.com/googlesamples/easypermissions/pull/78 which hasn't been released yet.

**Comment by usedlie** [comment]
@SUPERCILEX really?
but i notice that #78 is about fragment;
my problem is i have already granted all permissions ,but still EasyPermissions.hasPermissions(this, PERMISSIONS_ALL) return false.

forgive me , i just want to make sure this:)

**Comment by SUPERCILEX** [comment]
@usedlie `EasyPermissions.hasPermissions` shouldn't cause a crash related to a `ClassCastException` so I'm pretty sure #78 fixes it. You could always check by using [JitPack](https://jitpack.io/#googlesamples/easypermissions/178bc41bcc).

**Comment by usedlie** [comment]
@SUPERCILEX 
i try to delete the code about EasyPermissions;
try to ruquest permission in "system" way!
still ,i do these steps for over 10 times:

- delete app
- install app
- grant all the permissions very quickly

and i find there is one time that the app crash!
so i do these steps more time ,but it doesn't crash anymore;

so fucking weird!
so maybe the carsh is none of EasyPermissions's business.

anyway,EasyPermissions still work when i ruquest a permission nor a group of permissions,so 
thank you.
