### ISSUE TITLE
can not get the correct result

### ISSUE THREAD

**Issue by weilixing00** [googlesamples/easypermissions#88]
in HuaWei Mate7 (android 4.4) when i ask for camera permission, i choose refuse ,but show me i have the permission and can not call camera.   
what should i do ?

**Comment by gotoark** [comment]
Phones with Android Version<6 doesn't need Runtime Permission.Adding the Permissions in Manifest.xml is enough

**Comment by samtstern** [comment]
Thanks @gotoark.  

That is the correct answer, if you're running Android version earlier than 6.0 the runtime permissions code does nothing.
