### ISSUE TITLE
Issue if requested permission denied by user.

### ISSUE THREAD

**Issue by mdakram** [googlesamples/easypermissions#9]
It seems like there is an issue with this as it is calling request permission if user has denied the permission request. App perform slow, i am facing issue with text input if app user has denied the permission, logcat suggests App is requesting permission on continues basis.

**Comment by samtstern** [comment]
Can you describe exactly the problem you are seeing? Sounds like you're getting into an infinite loop but I can't replicate that behavior in my sample app (see the `app/` directory for the code I am using).

**Comment by Akash3hk** [comment]
I couldn't find any serious error. But It seems like you may have a trouble in the afterRequest loop.

**Comment by samtstern** [comment]
@Akash3hk are you having any issues?

**Comment by samtstern** [comment]
I am going to close this issue.  Please re-open if you can reproduce an error.
