### ISSUE TITLE
Mention that the library is on Jcenter

### ISSUE THREAD

**Issue by thevoiceless** [googlesamples/easypermissions#91]
It might be useful to note that you must have `jcenter()` in the build.gradle repositories. I kept getting `Error:Failed to resolve: pub.devrel:easypermissions:0.3.0` and was a bit dumbfounded until I realized I only had `mavenCentral()` 

Update: I now see [here](https://blog.bintray.com/2015/02/09/android-studio-migration-from-maven-central-to-jcenter/) that Jcenter has been the default for a while...I guess the code I was working on was older than I thought! Feel free to close this issue.

Unrelated: The [Android Quickstart](https://developers.google.com/classroom/quickstart/android) says to use 0.2.1

**Comment by samtstern** [comment]
@thevoiceless thanks for the update!  I will close this issue since yes, jCenter is the default.  And I just sent a pull request over to that docs page to bump the version they recommend, so thanks for the fix :+1:
