### ISSUE TITLE
Single callback instead of 2?

### ISSUE THREAD

**Issue by spekary** [googlesamples/easypermissions#93]
In a future version, could we have a single callback for the results, instead of onPermissionsGranted and onPermissionsDenied, perhaps something like 
```
void onPermissionsResults(int resquestCode, List<String> permsGranted, List<String> permsDenied)
```

This would be much more useful. As it stands, I cannot have one callback that will tell me that I can use to figure both whether all were granted, and if not, which ones were not granted, so I can know whether to continue my application, or notify the user and stop. With two callbacks, its much more difficult.

**Comment by samtstern** [comment]
@spekary I think that's a very good idea.  I too have come to prefer the single callback style in APIs (`onComplete` vs `onSuccess` and `onFailure`).  If you want to submit a PR I'd be happy to review, otherwise I'll put it on my list.

**Comment by refaelsh** [comment]
+1

**Comment by samtstern** [comment]
There was an attempt at this in #93 and it turned out to probably not be worthwhile.  We already have a single callback: the system callback.

Please see the discussion in that PR for more info.

**Comment by samtstern** [comment]
Sorry, #95 (wrong link above)
